/**
 * The control-plane API as its contract documents it. The types come from
 * packages/contracts/openapi/control-plane.openapi.yaml (`control-plane.gen.ts`,
 * regenerated by `pnpm gen:api`); the contract is checked against the service
 * on every test run (ADR-0021), so what compiles here is what the service does.
 *
 * The hand-written types the UI reads (`lib/types.ts`, the login form's
 * `AuthConfig`) must accept every response the contract allows:
 * `ClientTypesAcceptTheContract` does not compile when a response can carry
 * something the UI does not expect.
 */
import type { AuthConfig } from "@/components/auth/login-form";
import type { Agent, AgentVersion, ApiErrorBody, Me, Project } from "../types";
import * as contract from "./contract";
import type { Accepts } from "./contract";
import type { components, operations } from "./control-plane.gen";

export type ControlPlaneSchemas = components["schemas"];
export type ControlPlaneOperation = keyof operations;

/** The JSON body an operation accepts. */
export type BodyOf<Op extends ControlPlaneOperation> = contract.BodyOf<operations, Op>;

/** The JSON body of one documented response of an operation. */
export type ResponseOf<
  Op extends ControlPlaneOperation,
  Status extends keyof contract.ResponsesOf<operations, Op>,
> = contract.ResponseOf<operations, Op, Status>;

/** The query parameters an operation documents. */
export type QueryOf<Op extends ControlPlaneOperation> = contract.QueryOf<operations, Op>;

/** URL query parameters from the documented ones; unset and empty values are left out. */
export function queryOf<Op extends ControlPlaneOperation>(params: QueryOf<Op>): URLSearchParams {
  return contract.toQuery(params);
}

type S = ControlPlaneSchemas;

// Change sets and their impact (spec §21-22): the pages read the contract's
// own types.
export type ChangeSetSummary = S["ChangeSetSummary"];
export type ChangeSetPage = S["ChangeSetPage"];
export type ChangeSet = S["ChangeSet"];
export type CreatedChangeSet = S["CreatedChangeSet"];
export type ChangeItem = S["ChangeItem"];
export type ChangeSeed = S["ChangeSeed"];
export type ChangeImpact = S["ChangeImpact"];
export type ImpactScenario = S["ImpactScenario"];
export type ImpactGraphReason = S["ImpactGraphReason"];
export type ImpactSimilarity = S["ImpactSimilarity"];
export type ImpactAffected = S["ImpactAffected"];
export type ImpactLinked = S["ImpactLinked"];
export type ImpactProblem = S["ImpactProblem"];
export type ImpactPrivilege = S["ImpactPrivilege"];
export type GraphComponentRef = S["GraphComponent"];

// Releases and their gates (spec §28, §38, §91-92).
export type Release = S["Release"];
export type ReleasePage = S["ReleasePage"];
export type ReleaseDetail = S["ReleaseDetail"];
export type CreatedRelease = S["CreatedRelease"];
export type ReleaseGate = S["ReleaseGate"];
export type GateSummary = S["GateSummary"];
export type GateDecisionSummary = S["GateDecisionSummary"];
export type GateDecision = S["GateDecision"];
export type GateCounts = S["GateCounts"];
export type GateRule = S["GateRule"];
export type GateEvidence = S["GateEvidence"];
export type GateRatio = S["GateRatio"];
export type GateRiskIndex = S["GateRiskIndex"];
export type GateOverride = S["GateOverride"];
export type ReleaseSuiteEntry = S["ReleaseSuiteEntry"];
export type ResolvedGatePolicy = S["ResolvedGatePolicy"];
export type EffectiveOutcome = S["EffectiveOutcome"];
export type GateOutcome = S["GateOutcome"];
export type ChangeCounts = S["ChangeCounts"];

// The audit log (spec §75).
export type AuditEntry = S["AuditEntry"];
export type AuditPage = S["AuditPage"];

/** What the sign-in route reads from a development login. */
export interface DevLogin {
  token?: string;
  expires_at?: string;
  user?: unknown;
  role?: string;
  organization_id?: string;
}

// ------------------------------------------------------------------ checks

/** Each hand-written response type accepts the documented response of the operation that returns it. */
export type ClientTypesAcceptTheContract = [
  Accepts<AuthConfig, ResponseOf<"getAuthConfig", 200>>,
  Accepts<DevLogin, ResponseOf<"devLogin", 200>>,
  Accepts<Me, ResponseOf<"getMe", 200>>,
  Accepts<{ items: Project[] }, ResponseOf<"listProjects", 200>>,
  Accepts<{ items: Agent[] }, ResponseOf<"listAgents", 200>>,
  Accepts<{ items: AgentVersion[] }, ResponseOf<"listAgentVersions", 200>>,
  Accepts<ApiErrorBody, ControlPlaneSchemas["Error"]>,
];
