/**
 * The control-plane API as its contract documents it. The types come from
 * packages/contracts/openapi/control-plane.openapi.yaml (`control-plane.gen.ts`,
 * regenerated by `pnpm gen:api`); the contract is checked against the service
 * on every test run (ADR-0021), so what compiles here is what the service does.
 *
 * The hand-written types the UI reads (`lib/types.ts`, the login form's
 * `AuthConfig`) must accept every response the contract allows:
 * `ClientTypesAcceptTheContract` does not compile when a response can carry
 * something the UI does not expect.
 */
import type { AuthConfig } from "@/components/auth/login-form";
import type { Agent, AgentVersion, ApiErrorBody, Me, Project } from "../types";
import * as contract from "./contract";
import type { Accepts } from "./contract";
import type { components, operations } from "./control-plane.gen";

export type ControlPlaneSchemas = components["schemas"];
export type ControlPlaneOperation = keyof operations;

/** The JSON body an operation accepts. */
export type BodyOf<Op extends ControlPlaneOperation> = contract.BodyOf<operations, Op>;

/** The JSON body of one documented response of an operation. */
export type ResponseOf<
  Op extends ControlPlaneOperation,
  Status extends keyof contract.ResponsesOf<operations, Op>,
> = contract.ResponseOf<operations, Op, Status>;

/** What the sign-in route reads from a development login. */
export interface DevLogin {
  token?: string;
  expires_at?: string;
  user?: unknown;
  role?: string;
  organization_id?: string;
}

// ------------------------------------------------------------------ checks

/** Each hand-written response type accepts the documented response of the operation that returns it. */
export type ClientTypesAcceptTheContract = [
  Accepts<AuthConfig, ResponseOf<"getAuthConfig", 200>>,
  Accepts<DevLogin, ResponseOf<"devLogin", 200>>,
  Accepts<Me, ResponseOf<"getMe", 200>>,
  Accepts<{ items: Project[] }, ResponseOf<"listProjects", 200>>,
  Accepts<{ items: Agent[] }, ResponseOf<"listAgents", 200>>,
  Accepts<{ items: AgentVersion[] }, ResponseOf<"listAgentVersions", 200>>,
  Accepts<ApiErrorBody, ControlPlaneSchemas["Error"]>,
];
