/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View part of the graph
         * @description The components within `depth` hops of the focus, in either direction,
         *     at most `limit` of them (closest first), and the edges between them.
         *     Without a focus, the latest version of every agent is the focus. With
         *     `kinds`, other components are neither shown nor walked through. The
         *     totals count the whole project's graph.
         */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List components
         * @description The project's components ordered by kind, then key.
         */
        get: operations["listComponents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/components/{component_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a component and its relationships
         * @description The component, when it was first and last seen, and its relationships
         *     in both directions with the evidence for each (at most 200 per
         *     direction, most recently seen first; `truncated` says more exist).
         */
        get: operations["getComponent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/mappings/{tool}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Declare what a tool depends on
         * @description Replaces the tool's manual mapping: the systems it depends on and how
         *     (evidence `MANUAL`, confidence 1). An empty `depends_on` removes the
         *     mapping; relationships other sources support are kept. Requires the
         *     `graph.write` permission. Announced to the audit log.
         */
        put: operations["setToolMapping"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blast-radius": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute the blast radius of a change
         * @description Walks the graph from the changed components, up to who depends on
         *     them and down to what they act upon, and returns every component the
         *     change can influence with its path, score and severity, the
         *     scenarios, policies and evaluators linked to them, and the affected
         *     tools whose effects cannot be undone.
         *
         *     Only one agent version is entered: `scope`'s, or else each agent's
         *     latest. A component the graph does not know is listed in
         *     `unresolved`, never guessed. A prompt change with `mentions` makes
         *     the named tools direct; the agent's other tools are reached as
         *     indirect. Nothing is changed: the operation is a computation.
         */
        post: operations["computeBlastRadius"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /** Format: date-time */
        Timestamp: string;
        ToolName: string;
        /** @description Unique per kind within a project (a tool name, `agent@version`, `provider/model`, a prompt's hash…). */
        ComponentKey: string;
        Error: {
            error: {
                /** @description Stable, machine-readable (e.g. `INVALID_CHANGES`). */
                code: string;
                /** @description For people; may change. */
                message: string;
                /** @description Equals the `X-Request-Id` response header. */
                request_id: string;
                /** @description Code-specific context (the invalid field). */
                details?: Record<string, unknown>;
            };
        };
        /** @enum {string} */
        ComponentKind: "AGENT" | "AGENT_VERSION" | "PROMPT" | "MODEL" | "TOOL" | "MCP_SERVER" | "HTTP_API" | "SERVICE" | "DATABASE" | "QUEUE" | "EXTERNAL_SYSTEM" | "RETRIEVAL_SOURCE" | "DATASET" | "POLICY" | "SCENARIO" | "EVALUATOR";
        /**
         * @description Reads "from TYPE to": an agent version USES a tool, a tool WRITES a
         *     database, a tool is TESTED_BY a scenario.
         * @enum {string}
         */
        EdgeType: "USES" | "CALLS" | "READS" | "WRITES" | "PUBLISHES" | "CONSUMES" | "GUARDED_BY" | "EVALUATED_BY" | "TESTED_BY" | "DEPENDS_ON" | "RETRIEVES_FROM" | "CAN_MUTATE" | "VERSION_OF";
        /**
         * @description Why a relationship exists. `MANIFEST`, `MANUAL`, `SCENARIO` and
         *     `OBSERVED` (production traffic) are facts (confidence 1); `OPENAPI`
         *     (0.9) and `MCP` (0.8) describe interfaces; `INFERRED` (0.5) is never
         *     shown as certain.
         * @enum {string}
         */
        EvidenceSource: "MANIFEST" | "OPENAPI" | "MCP" | "OBSERVED" | "MANUAL" | "SCENARIO" | "INFERRED";
        Confidence: number;
        /** @enum {string} */
        Severity: "critical" | "high" | "medium" | "low";
        ComponentRef: {
            kind: components["schemas"]["ComponentKind"];
            key: components["schemas"]["ComponentKey"];
        };
        ComponentRefInput: {
            kind: components["schemas"]["ComponentKind"];
            key: string;
        };
        Component: {
            id: components["schemas"]["Uuid"];
            kind: components["schemas"]["ComponentKind"];
            key: components["schemas"]["ComponentKey"];
            label: string;
            /**
             * @description What the evidence says about the component: a tool's `risk`
             *     (manifest) or `imported_risk` (import), a system's `criticality`,
             *     an agent version's `agent`, `version`, `registered_at` and
             *     `latest`, a scenario's `severity` and `tags`.
             */
            attributes: Record<string, unknown>;
        };
        GraphEdge: {
            id: components["schemas"]["Uuid"];
            from: components["schemas"]["Uuid"];
            to: components["schemas"]["Uuid"];
            type: components["schemas"]["EdgeType"];
            confidence: components["schemas"]["Confidence"];
            sources: components["schemas"]["EvidenceSource"][];
            /** @description Whether any of its evidence is certain (not `INFERRED`). */
            certain: boolean;
        };
        GraphView: {
            focus: components["schemas"]["Component"][];
            /** @description The shown components, closest to the focus first; the focus is included. */
            nodes: components["schemas"]["Component"][];
            /** @description The edges between shown components. */
            edges: components["schemas"]["GraphEdge"][];
            depth: number;
            /** @description More components were within reach than `limit`. */
            truncated: boolean;
            totals: {
                /** @description The project's components per kind. */
                components: {
                    [key: string]: number;
                };
                edges: number;
            };
        };
        ComponentPage: {
            items: components["schemas"]["Component"][];
            next_cursor: string | null;
        };
        Evidence: {
            source: components["schemas"]["EvidenceSource"];
            /**
             * @description What asserted it: `manifest:<agent>@<version>`, `openapi:<name>`,
             *     `mcp:<server>`, `scenario:<name>`, `policy:<name>`,
             *     `mapping:<tool>` or `traces`.
             */
            source_ref: string;
            confidence: components["schemas"]["Confidence"];
            /** @description How many times production traces showed it (1 for declared evidence). */
            observations: number;
            /** @description Source-specific (an operation's `method` and `path`, the last trace id…). */
            detail: Record<string, unknown>;
            first_seen_at: components["schemas"]["Timestamp"];
            last_seen_at: components["schemas"]["Timestamp"];
        };
        Relation: {
            id: components["schemas"]["Uuid"];
            type: components["schemas"]["EdgeType"];
            /**
             * @description `out`: this component → the other; `in`: the other → this one.
             * @enum {string}
             */
            direction: "out" | "in";
            component: components["schemas"]["ComponentRef"];
            component_id: components["schemas"]["Uuid"];
            /** @description The other component's label. */
            label: string;
            confidence: components["schemas"]["Confidence"];
            sources: components["schemas"]["EvidenceSource"][];
            certain: boolean;
            evidence: components["schemas"]["Evidence"][];
        };
        ComponentDetail: {
            component: {
                id: components["schemas"]["Uuid"];
                project_id: components["schemas"]["Uuid"];
                kind: components["schemas"]["ComponentKind"];
                key: components["schemas"]["ComponentKey"];
                label: string;
                attributes: Record<string, unknown>;
                first_seen_at: components["schemas"]["Timestamp"];
                last_seen_at: components["schemas"]["Timestamp"];
            };
            relations: components["schemas"]["Relation"][];
            truncated: boolean;
        };
        Dependency: {
            /** @enum {string} */
            kind: "SERVICE" | "HTTP_API" | "DATABASE" | "QUEUE" | "EXTERNAL_SYSTEM" | "MCP_SERVER";
            name: string;
            /**
             * @default DEPENDS_ON
             * @enum {string}
             */
            relation?: "CALLS" | "READS" | "WRITES" | "PUBLISHES" | "CONSUMES" | "DEPENDS_ON" | "CAN_MUTATE";
            /** @enum {string} */
            criticality?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        };
        MappingRequest: {
            project_id: components["schemas"]["Uuid"];
            /** @description The tool's whole mapping; an empty list removes it. */
            depends_on: components["schemas"]["Dependency"][];
        };
        MappingResult: {
            tool: components["schemas"]["Component"];
            /** @description The tool's relationships this mapping supports. */
            mapped: components["schemas"]["Relation"][];
        };
        ChangeInput: {
            component: components["schemas"]["ComponentRefInput"];
            /** @enum {string} */
            change: "added" | "removed" | "modified";
            /** @description What changed, in words ("instructions changed"). */
            summary?: string;
            /** @description The tools a changed text names (the changed lines of a prompt). */
            mentions?: components["schemas"]["ToolName"][];
        };
        /** @description The agent version to enter instead of each agent's latest. */
        ScopeInput: {
            agent: string;
            version: string;
        };
        BlastRadiusRequest: {
            project_id: components["schemas"]["Uuid"];
            /** @description The changed components; two naming the same component are merged. */
            changes: components["schemas"]["ChangeInput"][];
            scope?: components["schemas"]["ScopeInput"] | null;
            /** @default 4 */
            max_depth?: number;
            /** @default 500 */
            max_nodes?: number;
        };
        Change: {
            component: components["schemas"]["ComponentRef"];
            /** @enum {string} */
            change: "added" | "removed" | "modified";
            summary?: string;
            mentions?: string[];
        };
        /** @description One hop of a path. The first step is the seed, with no edge. */
        Step: {
            component: components["schemas"]["ComponentRef"];
            label: string;
            edge: components["schemas"]["EdgeType"] | null;
            /**
             * @description `down`: what the previous component acts on; `up`: who depends on it.
             * @enum {string|null}
             */
            direction: "down" | "up" | null;
            confidence: components["schemas"]["Confidence"] | null;
            sources: components["schemas"]["EvidenceSource"][];
        };
        Affected: {
            component: components["schemas"]["ComponentRef"];
            label: string;
            attributes: Record<string, unknown>;
            /** @description The component is one of the changes. */
            seed: boolean;
            /** @description Not reached through an agent's tool that a prompt change does not mention. */
            direct: boolean;
            depth: number;
            /** @description Influence × criticality, decaying with depth. */
            score: number;
            severity: components["schemas"]["Severity"];
            /** @description Every hop of its path has certain evidence. */
            certain: boolean;
            /** @description Why it scored as it did, in words. */
            factors: string[];
            path: components["schemas"]["Step"][];
        };
        Reason: {
            via: components["schemas"]["ComponentRef"];
            via_label: string;
            direct: boolean;
            score: number;
            path: components["schemas"]["Step"][];
        };
        Linked: {
            component: components["schemas"]["ComponentRef"];
            label: string;
            /** @description A scenario's own severity. */
            severity?: string;
            /** @description The strongest reason's score, scaled by the scenario's severity. */
            weight: number;
            reasons: components["schemas"]["Reason"][];
        };
        BlastRadius: {
            seeds: components["schemas"]["Change"][];
            /** @description Changes naming components the graph does not know. */
            unresolved: components["schemas"]["Change"][];
            /** @description The seeds first, then by score (highest first), depth, kind and key. */
            affected: components["schemas"]["Affected"][];
            scenarios: components["schemas"]["Linked"][];
            policies: components["schemas"]["Linked"][];
            evaluators: components["schemas"]["Linked"][];
            /** @description Affected tools whose effects cannot be undone (`WRITE_IRREVERSIBLE`) or that act with administrative rights. */
            irreversible_actions: components["schemas"]["Affected"][];
            max_depth: number;
            /** @description More components were within reach than `max_nodes`. */
            truncated: boolean;
        };
        BlastRadiusResponse: {
            blast_radius: components["schemas"]["BlastRadius"];
        };
    };
    responses: {
        /**
         * @description The request is invalid: `INVALID_PARAMETER` (`details.field`),
         *     `INVALID_CURSOR` or `INVALID_IDEMPOTENCY_KEY`.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description `INVALID_MAPPING` (an unknown dependency kind, relation or
         *     criticality, more than 50 dependencies, or no `depends_on`;
         *     `details.field`), `INVALID_PARAMETER`, `INVALID_JSON` (including an
         *     unknown field), `EMPTY_BODY` or `INVALID_IDEMPOTENCY_KEY`.
         */
        MappingInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description `INVALID_CHANGES` (none or more than 100 changes, an unknown kind, a
         *     key that is not 1 to 300 printable characters, a change that is not
         *     added, removed or modified, a mention that is not a tool name;
         *     `details.field`), `INVALID_SCOPE`, `INVALID_PARAMETER` (`max_depth`,
         *     `max_nodes`), `INVALID_JSON`, `EMPTY_BODY` or
         *     `INVALID_IDEMPOTENCY_KEY`.
         */
        BlastRadiusInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid credential (`UNAUTHENTICATED`). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The credential lacks the permission (`FORBIDDEN`; `details.required_permission`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The project or component does not exist or is outside the caller's projects (`NOT_FOUND`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The first request with this `Idempotency-Key` is still running (`IDEMPOTENCY_IN_PROGRESS`). */
        IdempotencyInProgress: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request body is too large (`PAYLOAD_TOO_LARGE`). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The body is not `application/json` (`UNSUPPORTED_MEDIA_TYPE`). */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The `Idempotency-Key` was used for a different request (`IDEMPOTENCY_KEY_REUSED`). */
        IdempotencyKeyReused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests (`RATE_LIMITED`). */
        RateLimited: {
            headers: {
                /** @description Seconds to wait. */
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description An unexpected error (`INTERNAL`); quote the `request_id`. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The graph service is not reachable from the control plane (`UPSTREAM_UNAVAILABLE`). */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The graph service is not configured on this control plane
         *     (`SERVICE_NOT_CONFIGURED`) or its database is unavailable
         *     (`UNAVAILABLE`).
         */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description One key per user action (ADR-0019). A repeat of the same request
         *     returns the stored response with `Idempotent-Replayed: true`; the same
         *     key with a different request answers `422`; while the first request
         *     runs, `409`. Keys expire after 24 hours.
         */
        IdempotencyKey: string;
        /** @description The organization to act in, for credentials that belong to several. */
        Organization: components["schemas"]["Uuid"];
        /** @description The project whose graph to read. A project outside the caller's access answers `404`. */
        Project: components["schemas"]["Uuid"];
        /** @description The `next_cursor` of the previous page. */
        Cursor: string;
        Limit: number;
        ComponentId: components["schemas"]["Uuid"];
    };
    requestBodies: never;
    headers: {
        /** @description `true` when the response is the stored answer to an earlier request with the same `Idempotency-Key`. */
        IdempotentReplayed: "true";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGraph: {
        parameters: {
            query: {
                /** @description The project whose graph to read. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
                /** @description The component to centre on (a component id). Unknown ids answer `404`. */
                focus?: components["schemas"]["Uuid"];
                depth?: number;
                /** @description The most components shown. */
                limit?: number;
                /** @description Comma-separated component kinds to show (e.g. `TOOL,SERVICE,DATABASE`). */
                kinds?: string;
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bounded view. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    listComponents: {
        parameters: {
            query: {
                /** @description The project whose graph to read. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
                kind?: components["schemas"]["ComponentKind"];
                /** @description Matches the key or the label (substring, case-insensitive). */
                q?: string;
                /** @description The `next_cursor` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of components. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getComponent: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                component_id: components["parameters"]["ComponentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The component. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    setToolMapping: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description One key per user action (ADR-0019). A repeat of the same request
                 *     returns the stored response with `Idempotent-Replayed: true`; the same
                 *     key with a different request answers `422`; while the first request
                 *     runs, `409`. Keys expire after 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                tool: components["schemas"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingRequest"];
            };
        };
        responses: {
            /** @description The tool and the relationships the mapping now supports. */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingResult"];
                };
            };
            400: components["responses"]["MappingInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    computeBlastRadius: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description One key per user action (ADR-0019). A repeat of the same request
                 *     returns the stored response with `Idempotent-Replayed: true`; the same
                 *     key with a different request answers `422`; while the first request
                 *     runs, `409`. Keys expire after 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlastRadiusRequest"];
            };
        };
        responses: {
            /** @description The bounded blast radius. */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlastRadiusResponse"];
                };
            };
            400: components["responses"]["BlastRadiusInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
}
