/**
 * The dependency graph API as its contract documents it. The types come from
 * packages/contracts/openapi/graph-service.openapi.yaml (`graph.gen.ts`,
 * regenerated by `pnpm gen:api`); the contract is checked against the service
 * on every test run (ADR-0021). The graph pages read the contract's own types.
 */
import * as contract from "./contract";
import type { components, operations } from "./graph.gen";

export type GraphSchemas = components["schemas"];
export type GraphOperation = keyof operations;

/** The query parameters an operation documents. */
export type QueryOf<Op extends GraphOperation> = contract.QueryOf<operations, Op>;

/** URL query parameters from the documented ones; unset and empty values are left out. */
export function queryOf<Op extends GraphOperation>(params: QueryOf<Op>): URLSearchParams {
  return contract.toQuery(params);
}

type S = GraphSchemas;

export type ComponentKind = S["ComponentKind"];
export type EdgeType = S["EdgeType"];
export type EvidenceSource = S["EvidenceSource"];
export type GraphComponent = S["Component"];
export type GraphEdge = S["GraphEdge"];
export type GraphView = S["GraphView"];
export type ComponentPage = S["ComponentPage"];
export type ComponentDetail = S["ComponentDetail"];
export type Relation = S["Relation"];
export type Evidence = S["Evidence"];
export type PathStep = S["Step"];
