/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tool-endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tool endpoints
         * @description The project's registered tools, by name.
         */
        get: operations["listToolEndpoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool-endpoints/{tool}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: components["parameters"]["Tool"];
            };
            cookie?: never;
        };
        /** Read a tool endpoint */
        get: operations["getToolEndpoint"];
        /**
         * Register or replace a tool endpoint
         * @description Registers the tool (`201`) or replaces its endpoint (`200`); needs
         *     `policy.write`. The URL's host must be in the egress allowlist
         *     (`RUNTIME_EGRESS_ALLOWED_HOSTS`, or `RUNTIME_EGRESS_PRIVATE_HOSTS` for
         *     an internal service); every call is checked again when it dials.
         *     An irreversible tool requires an idempotency key unless
         *     `idempotency: optional` is set. Audited (`tool_endpoint.registered` or
         *     `tool_endpoint.updated`).
         */
        put: operations["putToolEndpoint"];
        post?: never;
        /**
         * Remove a tool endpoint
         * @description The tool can no longer be called through the gateway (`404
         *     TOOL_NOT_REGISTERED`); its policies and decisions are kept. Needs
         *     `policy.write`; audited (`tool_endpoint.removed`).
         */
        delete: operations["deleteToolEndpoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List policies
         * @description The project's policies by name, optionally those guarding one tool.
         */
        get: operations["listPolicies"];
        put?: never;
        /**
         * Create a policy
         * @description Stores a policy document (YAML or JSON, `apiVersion:
         *     agenttwin.dev/v1`, `kind: Policy`) as version 1 of a new policy named
         *     by its `metadata.name`, guarding `spec.tool`. Every rule is compiled
         *     and type-checked; nothing is activated. Needs `policy.write`; audited
         *     (`policy.created`).
         */
        post: operations["createPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a policy
         * @description Decides a draft document, or a saved version, against its own tests
         *     and the extra `cases`, and around every numeric threshold its rules
         *     compare against: `args.amount > 100` is decided at 99, 99.99, 100,
         *     100.01 and 101 (one hundredth either side of a decimal threshold; one
         *     call either side of `trace.calls`). The boundaries start from `base`,
         *     else from the first test's action. Reports the rules no test decided
         *     and whether the version could be activated for the tool as
         *     registered. Needs `policy.test`; nothing is stored.
         */
        post: operations["testPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: components["parameters"]["PolicyId"];
            };
            cookie?: never;
        };
        /**
         * Read a policy
         * @description The policy, its active version and every version (newest first).
         */
        get: operations["getPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: components["parameters"]["PolicyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a policy version
         * @description Stores the document as the policy's next version (`201`). Its
         *     `metadata.name` and `spec.tool` must stay the policy's. A document
         *     that decides exactly what the latest version decides (the same
         *     `spec_hash`) returns that version (`200`, `created: false`). Versions
         *     are immutable; the active one does not change. Needs `policy.write`;
         *     audited (`policy.version_created`).
         */
        post: operations["addPolicyVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: components["parameters"]["PolicyId"];
                version: number;
            };
            cookie?: never;
        };
        /**
         * Read a policy version
         * @description The document as written and as read (defaults filled), the variables
         *     its rules can use and the numeric thresholds they compare against.
         */
        get: operations["getPolicyVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: components["parameters"]["PolicyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate a policy version
         * @description Makes the version the policy's active one, from the next call on.
         *     Refused (`422 POLICY_NOT_ACTIVATABLE`, `details.problems`) unless the
         *     version has tests and every test passes; `fail_open` only for a tool
         *     registered as `READ`. Activating the active version changes nothing.
         *     Needs `policy.activate`; publishes `policy.activated.v1` and is
         *     audited (`policy.activated`).
         */
        post: operations["activatePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: components["parameters"]["PolicyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate a policy
         * @description The policy no longer guards its tool, from the next call on. A reason
         *     is required: removing a guard is audited (`policy.deactivated`).
         *     Needs `policy.activate`.
         */
        post: operations["deactivatePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List approval requests
         * @description Newest first. `status` is the status as of now: `EXPIRED` includes
         *     open requests past their expiry, which `PENDING` and `APPROVED`
         *     exclude.
         */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        /**
         * Read an approval request
         * @description What the agent is trying to do (the tool, its risk tier, the redacted
         *     arguments), why it needs approval (the policy, rule and reason), the
         *     decision that asked, the expiry, the trace, and every call that
         *     presented the approval's token with how its arguments differ from the
         *     approved ones (spec §41.9).
         */
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{approval_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve the action
         * @description Approves this exact action, with a reason. The agent that asked then
         *     claims a token and the action runs once. A request that is no longer
         *     pending answers `409 APPROVAL_CLOSED` (`details.status`); one past its
         *     expiry is closed as `EXPIRED`. Needs `approval.decide`; audited
         *     (`approval.approved`).
         */
        post: operations["approveApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{approval_id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deny the action
         * @description Denies this action, with a reason; the agent's token claim answers
         *     `403 APPROVAL_DENIED`. The same rules as approving. Needs
         *     `approval.decide`; audited (`approval.denied`).
         */
        post: operations["denyApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List decisions
         * @description Every call the gateway decided, newest first.
         */
        get: operations["listPolicyDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy-decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        /** Read a decision */
        get: operations["getPolicyDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/v1/tools/{tool}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: components["parameters"]["Tool"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Call a tool through the gateway
         * @description The body is the tool's arguments — exactly what the tool itself takes
         *     — so an agent opts in by changing its tools base URL. The tool's
         *     active policies decide the call:
         *
         *     * **allow** / **allow_with_limits** (a lower timeout, a smaller
         *       response cap): the arguments are forwarded (http: `POST` of their
         *       canonical JSON; mcp: a JSON-RPC `tools/call`) with the
         *       `Idempotency-Key`, `traceparent` and the endpoint's forwarded
         *       headers, and the tool's status and body are returned.
         *     * **require_approval**: `403 APPROVAL_REQUIRED` with
         *       `details.approval_id` and `details.expires_at`. Once a person
         *       approves, the agent claims a token and sends it in
         *       `X-AgentTwin-Approval-Token` with the same call: the approved action
         *       runs once. A different action (`403 APPROVAL_MISMATCH`, with
         *       `details.changes`) is recorded on the approval and does not use it.
         *       An approval never overrides a `deny`.
         *     * **deny**: `403 POLICY_DENIED`.
         *
         *     With an `Idempotency-Key` (scoped to the project and tool), a call
         *     that already completed for the same action returns the stored
         *     response (`Idempotent-Replayed: true`) without calling the tool; the
         *     same key for another action is `409 IDEMPOTENCY_KEY_REUSED`; while it
         *     runs, `409 IDEMPOTENCY_IN_PROGRESS`. A timeout leaves the outcome
         *     unknown: the next call with the key is forwarded again, for the tool
         *     to deduplicate.
         *
         *     Every decided call is recorded; the decision is in the response
         *     headers. `deny` and `require_approval` publish
         *     `policy.violation_detected.v1`.
         */
        post: operations["invokeTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/v1/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        /**
         * Read an approval request (agent side)
         * @description The status of a request the agent's call opened, for the agent to poll.
         */
        get: operations["getGatewayApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/v1/approvals/{approval_id}/token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim the token of an approved request
         * @description Mints the token the approved action runs with — 32 random bytes,
         *     stored only as a hash, valid for at most 10 minutes and never past
         *     the approval's expiry. Only the caller that asked for the approval
         *     may claim it (`403 NOT_REQUESTER`); claiming again voids the previous
         *     token. `409 APPROVAL_PENDING` while a person has not decided;
         *     `403 APPROVAL_DENIED`, `APPROVAL_EXPIRED` or `APPROVAL_USED`
         *     otherwise. Audited (`approval.token_issued`).
         */
        post: operations["claimApprovalToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /** Format: date-time */
        Timestamp: string;
        ToolName: string;
        TraceId: string;
        Hash: string;
        /** @enum {string} */
        Risk: "READ" | "WRITE_REVERSIBLE" | "WRITE_IRREVERSIBLE" | "EXECUTE" | "ADMIN";
        /** @enum {string} */
        Effect: "allow" | "allow_with_limits" | "require_approval" | "deny";
        /**
         * @description `forwarded` (sent, not yet answered), `executed` (the tool answered),
         *     `failed` (it failed, timed out or answered 5xx), `replayed` (a stored
         *     answer), `denied`, `approval_required`, `approval_refused` (a token
         *     that did not let the call run).
         * @enum {string}
         */
        Outcome: "forwarded" | "executed" | "failed" | "replayed" | "denied" | "approval_required" | "approval_refused";
        /** @enum {string} */
        ApprovalStatus: "PENDING" | "APPROVED" | "DENIED" | "EXPIRED" | "USED";
        Error: {
            error: {
                code: string;
                message: string;
                request_id: string;
                details?: Record<string, unknown>;
            };
        };
        /** @description The gateway's error, or the tool's own answer with that status. */
        ErrorOrToolAnswer: components["schemas"]["Error"] | components["schemas"]["ToolAnswer"];
        /** @description The tool's arguments, exactly as the tool takes them. */
        ToolArguments: Record<string, unknown>;
        /**
         * @description What the tool answered: JSON as `application/json`, text as
         *     `text/plain`, anything else as `application/octet-stream` (never
         *     HTML).
         */
        ToolAnswer: unknown;
        ToolEndpoint: {
            tool: components["schemas"]["ToolName"];
            /** @enum {string} */
            kind: "http" | "mcp";
            url: string;
            risk: components["schemas"]["Risk"];
            timeout_ms: number;
            /** @enum {string} */
            idempotency: "required" | "optional";
            forward_headers: string[];
            updated_by: string;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        ToolEndpointInput: {
            project_id: components["schemas"]["Uuid"];
            /**
             * @default http
             * @enum {string}
             */
            kind?: "http" | "mcp";
            /** @description An absolute http(s) URL in the egress allowlist; for `http`, the arguments are POSTed to it. */
            url: string;
            risk: components["schemas"]["Risk"];
            /** @default 10000 */
            timeout_ms?: number;
            /**
             * @description Defaults to `required` for `WRITE_IRREVERSIBLE`, else `optional`.
             * @enum {string}
             */
            idempotency?: "required" | "optional";
            /** @description Request headers passed to the tool (never credentials or the gateway's own). */
            forward_headers?: string[];
        };
        ToolEndpointPage: {
            items: components["schemas"]["ToolEndpoint"][];
        };
        VersionRef: {
            id: components["schemas"]["Uuid"];
            version: number;
        };
        Policy: {
            id: components["schemas"]["Uuid"];
            name: string;
            tool: components["schemas"]["ToolName"];
            description: string;
            latest_version: number;
            /** @description The active version, or `null` when the policy guards nothing. */
            active: components["schemas"]["VersionRef"] | null;
            activated_by: string | null;
            activated_at: components["schemas"]["Timestamp"] | null;
            created_by: string;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        PolicyPage: {
            items: components["schemas"]["Policy"][];
        };
        VersionSummary: {
            id: components["schemas"]["Uuid"];
            version: number;
            spec_hash: components["schemas"]["Hash"];
            created_by: string;
            created_at: components["schemas"]["Timestamp"];
            active: boolean;
        };
        PolicyDetail: components["schemas"]["Policy"] & {
            versions: components["schemas"]["VersionSummary"][];
        };
        /**
         * @description The document as read, defaults filled (`apiVersion`, `kind`,
         *     `metadata`, `spec`: `tool`, `default`, `failMode`, `rules`, `limits`,
         *     `approval`, `tests`).
         */
        PolicySpec: Record<string, unknown>;
        PolicyVersion: {
            id: components["schemas"]["Uuid"];
            policy_id: components["schemas"]["Uuid"];
            version: number;
            /** @description The document as its author wrote it. */
            document: string;
            spec: components["schemas"]["PolicySpec"];
            spec_hash: components["schemas"]["Hash"];
            created_by: string;
            created_at: components["schemas"]["Timestamp"];
            active: boolean;
        };
        PolicyVersionDetail: components["schemas"]["PolicyVersion"] & {
            /** @description What a rule can read. */
            variables: string[];
            thresholds: components["schemas"]["Threshold"][];
        };
        PolicyDocumentInput: {
            project_id: components["schemas"]["Uuid"];
            /** @description The policy document, YAML or JSON. */
            document: string;
        };
        PolicyCreated: {
            policy: components["schemas"]["Policy"];
            version: components["schemas"]["PolicyVersion"];
        };
        PolicyVersionAdded: {
            policy: components["schemas"]["Policy"];
            version: components["schemas"]["PolicyVersion"];
            created: boolean;
        };
        ActivateInput: {
            project_id: components["schemas"]["Uuid"];
            version: number;
            reason?: string;
        };
        ReasonInput: {
            project_id: components["schemas"]["Uuid"];
            reason: string;
        };
        /** @description The action's context, the arguments aside. */
        TestContext: {
            agent?: string;
            agentVersion?: string;
            environment?: string;
            subject?: string;
            risk?: string;
            traceId?: string;
            traceCalls?: number;
        };
        PolicyTestCase: {
            name: string;
            args?: Record<string, unknown>;
            context?: components["schemas"]["TestContext"];
            expect: components["schemas"]["Effect"];
            /** @description The rule expected to decide. */
            rule?: string;
        };
        PolicyTestInput: {
            project_id: components["schemas"]["Uuid"];
            /** @description A draft document (or give `policy_id` and `version`). */
            document?: string;
            policy_id?: components["schemas"]["Uuid"];
            version?: number;
            cases?: components["schemas"]["PolicyTestCase"][];
            /** @description The action the boundaries start from. */
            base?: {
                args?: Record<string, unknown>;
                context?: components["schemas"]["TestContext"];
            };
        };
        Limits: {
            timeoutMs?: number;
            maxResponseBytes?: number;
        };
        Match: {
            rule: string;
            effect: components["schemas"]["Effect"];
            message?: string;
        };
        PolicyDecision: {
            policy: string;
            effect: components["schemas"]["Effect"];
            /** @description The rule that decided; absent when the default applied. */
            rule?: string;
            message: string;
            /** @description Every rule whose condition held, in order. */
            matched: components["schemas"]["Match"][];
            /** @description Rules that could not be evaluated (the fail mode applied). */
            errors?: {
                rule: string;
                error: string;
            }[];
            fail_mode_applied: boolean;
            limits?: components["schemas"]["Limits"];
        };
        TestResult: {
            name: string;
            expect: components["schemas"]["Effect"];
            expect_rule?: string;
            decision: components["schemas"]["PolicyDecision"];
            passed: boolean;
            /** @description Why the test failed. */
            why?: string;
        };
        Threshold: {
            rule: string;
            /** @description `args.<name>[.<name>…]` or `trace.calls`. */
            path: string;
            op: string;
            value: number;
            integer: boolean;
        };
        Boundary: components["schemas"]["Threshold"] & {
            probes: {
                value: number;
                effect: components["schemas"]["Effect"];
                rule?: string;
                fail_mode_applied: boolean;
            }[];
        };
        Problem: {
            field: string;
            message: string;
        };
        PolicyTestReport: {
            tool: components["schemas"]["ToolName"];
            spec_hash: components["schemas"]["Hash"];
            passed: boolean;
            results: components["schemas"]["TestResult"][];
            boundaries: components["schemas"]["Boundary"][];
            /** @description Rules no test decided. */
            undecided: string[];
            /** @description The tool's risk tier as registered, `null` when it is not. */
            tool_risk: components["schemas"]["Risk"] | null;
            activatable: boolean;
            activation_problems: components["schemas"]["Problem"][];
        };
        Approval: {
            id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            tool: components["schemas"]["ToolName"];
            risk: components["schemas"]["Risk"];
            agent: string;
            agent_version: string;
            environment: string;
            trace_id: components["schemas"]["TraceId"] | null;
            action_hash: components["schemas"]["Hash"];
            /** @description The action's arguments, redacted. */
            arguments: Record<string, unknown>;
            /** @description A one-line description of the action. */
            summary: string;
            policy: string;
            policy_version_id: components["schemas"]["Uuid"] | null;
            rule: string;
            /** @description Why the action needs approval (the rule's message). */
            reason: string;
            decision_id: components["schemas"]["Uuid"];
            status: components["schemas"]["ApprovalStatus"];
            requested_by: string;
            expires_at: components["schemas"]["Timestamp"];
            decided_by: string | null;
            decided_at: components["schemas"]["Timestamp"] | null;
            decision_reason: string | null;
            used_at: components["schemas"]["Timestamp"] | null;
            used_decision_id: components["schemas"]["Uuid"] | null;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        ApprovalPage: {
            items: components["schemas"]["Approval"][];
            next_cursor?: string;
        };
        Change: {
            /** @description The argument (`amount`, `items[1].sku`). */
            path: string;
            /** @description The approved value (absent when the argument was not there). */
            before?: unknown;
            /** @description The attempted value (absent when the argument is gone). */
            after?: unknown;
            added?: boolean;
            removed?: boolean;
        };
        Attempt: {
            id: components["schemas"]["Uuid"];
            /** @enum {string} */
            result: "executed" | "mismatch" | "used" | "expired" | "not_approved";
            action_hash: components["schemas"]["Hash"];
            arguments: Record<string, unknown>;
            subject: string;
            trace_id: string | null;
            decision_id: components["schemas"]["Uuid"] | null;
            created_at: components["schemas"]["Timestamp"];
            /** @description How the attempted arguments differ from the approved ones. */
            changes: components["schemas"]["Change"][];
        };
        ApprovalDetail: components["schemas"]["Approval"] & {
            /** @description The decision that asked for the approval. */
            decision: components["schemas"]["Decision"] | null;
            /** @description The decision that executed the approved action. */
            used_decision: components["schemas"]["Decision"] | null;
            attempts: components["schemas"]["Attempt"][];
        };
        ApprovalToken: {
            approval_id: components["schemas"]["Uuid"];
            token: string;
            expires_at: components["schemas"]["Timestamp"];
        };
        RecordedDecision: components["schemas"]["PolicyDecision"] & {
            policy_version_id: components["schemas"]["Uuid"];
            version: number;
        };
        Decision: {
            id: components["schemas"]["Uuid"];
            tool: components["schemas"]["ToolName"];
            risk: components["schemas"]["Risk"];
            agent: string;
            agent_version: string;
            environment: string;
            /** @description Who called (`apikey:<id>`). */
            subject: string;
            trace_id: components["schemas"]["TraceId"] | null;
            action_hash: components["schemas"]["Hash"];
            /** @description The arguments, redacted. */
            arguments: Record<string, unknown>;
            summary: string;
            /** @description The combined effect; `null` for a replay (decided by the call it replays). */
            effect: components["schemas"]["Effect"] | null;
            outcome: components["schemas"]["Outcome"];
            policy: string | null;
            policy_version_id: components["schemas"]["Uuid"] | null;
            rule: string | null;
            message: string;
            /** @description What each active policy decided. */
            decisions: components["schemas"]["RecordedDecision"][];
            fail_mode_applied: boolean;
            approval_id: components["schemas"]["Uuid"] | null;
            idempotency_key: string | null;
            limits: components["schemas"]["Limits"] | null;
            upstream_status: number | null;
            error_code: string | null;
            latency_ms: number | null;
            created_at: components["schemas"]["Timestamp"];
            completed_at: components["schemas"]["Timestamp"] | null;
        };
        DecisionPage: {
            items: components["schemas"]["Decision"][];
            next_cursor?: string;
        };
    };
    responses: {
        /**
         * @description The request is invalid: `INVALID_PARAMETER` (`details.field`),
         *     `INVALID_CURSOR`, `PROJECT_REQUIRED` or `INVALID_IDEMPOTENCY_KEY`.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description `INVALID_ENDPOINT` (kind, risk, timeout, idempotency, forwarded
         *     headers or URL; `details.field`), `EGRESS_NOT_ALLOWED` (the URL's host
         *     is not in the egress allowlist, a private or metadata address,
         *     credentials in the URL, or plain http where it is not allowed),
         *     `INVALID_PARAMETER`, `INVALID_JSON` (including an unknown field),
         *     `EMPTY_BODY` or `INVALID_IDEMPOTENCY_KEY`.
         */
        EndpointInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description `INVALID_POLICY` (`details.problems`: every problem with its field —
         *     schema, names, rules that do not compile or are not boolean, tests;
         *     a new version that renames the policy or retargets its tool),
         *     `INVALID_PARAMETER`, `INVALID_JSON`, `EMPTY_BODY` or
         *     `INVALID_IDEMPOTENCY_KEY`.
         */
        PolicyInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description `INVALID_POLICY` (a draft document that is not valid;
         *     `details.problems`), `INVALID_CASES` (`details.field`),
         *     `INVALID_PARAMETER` (neither or both of a document and a saved
         *     version), `INVALID_JSON`, `EMPTY_BODY` or `INVALID_IDEMPOTENCY_KEY`.
         */
        PolicyTestInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description `INVALID_REASON` (missing or longer than 2000 characters),
         *     `INVALID_PARAMETER`, `INVALID_JSON`, `EMPTY_BODY` or
         *     `INVALID_IDEMPOTENCY_KEY`.
         */
        ReasonInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid credential (`UNAUTHENTICATED`). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The credential lacks the permission (`FORBIDDEN`; `details.required_permission`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The project or resource does not exist or is outside the caller's projects (`NOT_FOUND`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description A policy of that name exists in the project (`POLICY_EXISTS`; add a
         *     version to it), or the first request with this `Idempotency-Key` is
         *     still running (`IDEMPOTENCY_IN_PROGRESS`).
         */
        PolicyExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The version cannot be activated (`POLICY_NOT_ACTIVATABLE`;
         *     `details.problems`: no tests, a failing test, `fail_open` on a tool
         *     that is not `READ`), or the `Idempotency-Key` was used for a
         *     different request (`IDEMPOTENCY_KEY_REUSED`).
         */
        NotActivatable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The request is no longer pending (`APPROVAL_CLOSED`;
         *     `details.status`), or the first request with this `Idempotency-Key`
         *     is still running (`IDEMPOTENCY_IN_PROGRESS`).
         */
        ApprovalClosed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A person has not decided yet (`APPROVAL_PENDING`); poll and claim again. */
        ApprovalPending: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description `NOT_REQUESTER`, `APPROVAL_DENIED` (`details.reason`),
         *     `APPROVAL_EXPIRED`, `APPROVAL_USED`, or `FORBIDDEN` (no
         *     `runtime:invoke`).
         */
        ClaimRefused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The first request with this `Idempotency-Key` is still running (`IDEMPOTENCY_IN_PROGRESS`). */
        IdempotencyInProgress: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request body is too large (`PAYLOAD_TOO_LARGE`). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The body is not `application/json` (`UNSUPPORTED_MEDIA_TYPE`). */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The `Idempotency-Key` was used for a different request (`IDEMPOTENCY_KEY_REUSED`). */
        IdempotencyKeyReused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests (`RATE_LIMITED`). */
        RateLimited: {
            headers: {
                /** @description Seconds to wait. */
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description An unexpected error (`INTERNAL`); quote the `request_id`. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The runtime gateway is not reachable from the control plane (`UPSTREAM_UNAVAILABLE`). */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The runtime gateway is not configured on this control plane
         *     (`SERVICE_NOT_CONFIGURED`) or its database is unavailable
         *     (`UNAVAILABLE`).
         */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The gateway refused the call before deciding it: `INVALID_ARGUMENTS`
         *     (not one JSON object), `INVALID_CONTEXT` (`details.problems`: a
         *     header that cannot be used), `PROJECT_REQUIRED`,
         *     `IDEMPOTENCY_KEY_REQUIRED`, `INVALID_PARAMETER` — or the tool's own
         *     `400` answer.
         */
        InvokeInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorOrToolAnswer"];
                "text/plain": components["schemas"]["ToolAnswer"];
                "application/octet-stream": components["schemas"]["ToolAnswer"];
            };
        };
        /**
         * @description The decision refused the call: `POLICY_DENIED`, `APPROVAL_REQUIRED`
         *     (`details.approval_id`, `details.expires_at`), `APPROVAL_MISMATCH`
         *     (`details.changes`), `APPROVAL_USED`, `APPROVAL_EXPIRED`,
         *     `APPROVAL_NOT_APPROVED`, `APPROVAL_TOKEN_INVALID`,
         *     `APPROVAL_TOKEN_EXPIRED` (claim a new token); the decision is in
         *     the headers. `FORBIDDEN` without `runtime:invoke` — or the tool's own
         *     `403` answer.
         */
        InvokeRefused: {
            headers: {
                "X-AgentTwin-Decision": components["headers"]["Decision"];
                "X-AgentTwin-Decision-Id": components["headers"]["DecisionId"];
                "X-AgentTwin-Policy": components["headers"]["Policy"];
                "X-AgentTwin-Policy-Version": components["headers"]["PolicyVersion"];
                "X-AgentTwin-Policy-Rule": components["headers"]["PolicyRule"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorOrToolAnswer"];
                "text/plain": components["schemas"]["ToolAnswer"];
                "application/octet-stream": components["schemas"]["ToolAnswer"];
            };
        };
        /**
         * @description The tool is not registered with the gateway (`TOOL_NOT_REGISTERED`),
         *     the project is outside the key's (`NOT_FOUND`) — or the tool's own
         *     `404` answer.
         */
        ToolNotRegistered: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorOrToolAnswer"];
                "text/plain": components["schemas"]["ToolAnswer"];
                "application/octet-stream": components["schemas"]["ToolAnswer"];
            };
        };
        /**
         * @description `IDEMPOTENCY_KEY_REUSED` (the key was used for another action) or
         *     `IDEMPOTENCY_IN_PROGRESS` — or the tool's own `409` answer.
         */
        InvokeConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorOrToolAnswer"];
                "text/plain": components["schemas"]["ToolAnswer"];
                "application/octet-stream": components["schemas"]["ToolAnswer"];
            };
        };
        /** @description The arguments exceed 256 KiB (`PAYLOAD_TOO_LARGE`) — or the tool's own `413` answer. */
        InvokePayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorOrToolAnswer"];
                "text/plain": components["schemas"]["ToolAnswer"];
                "application/octet-stream": components["schemas"]["ToolAnswer"];
            };
        };
        /** @description Too many requests at the edge (`RATE_LIMITED`) — or the tool's own `429` answer. */
        InvokeRateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorOrToolAnswer"];
                "text/plain": components["schemas"]["ToolAnswer"];
                "application/octet-stream": components["schemas"]["ToolAnswer"];
            };
        };
        /** @description An unexpected error (`INTERNAL`) — or the tool's own `500` answer. */
        InvokeInternal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorOrToolAnswer"];
                "text/plain": components["schemas"]["ToolAnswer"];
                "application/octet-stream": components["schemas"]["ToolAnswer"];
            };
        };
        /**
         * @description The tool could not be called: `TOOL_UNAVAILABLE`, `EGRESS_BLOCKED`
         *     (its address is refused when dialled), `TOOL_RESPONSE_TOO_LARGE`,
         *     `TOOL_PROTOCOL_ERROR` (an MCP server's error) — or the tool's own
         *     `502` answer, or the edge's `UPSTREAM_UNAVAILABLE`.
         */
        ToolFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorOrToolAnswer"];
                "text/plain": components["schemas"]["ToolAnswer"];
                "application/octet-stream": components["schemas"]["ToolAnswer"];
            };
        };
        /**
         * @description The gateway could not decide the call (`GATEWAY_UNAVAILABLE`):
         *     nothing was forwarded — or the tool's own `503` answer, or the edge's
         *     `SERVICE_NOT_CONFIGURED`.
         */
        GatewayUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorOrToolAnswer"];
                "text/plain": components["schemas"]["ToolAnswer"];
                "application/octet-stream": components["schemas"]["ToolAnswer"];
            };
        };
        /**
         * @description The tool did not answer in time (`TOOL_TIMEOUT`): its outcome is
         *     unknown; retry with the same `Idempotency-Key` — or the tool's own
         *     `504` answer.
         */
        ToolTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorOrToolAnswer"];
                "text/plain": components["schemas"]["ToolAnswer"];
                "application/octet-stream": components["schemas"]["ToolAnswer"];
            };
        };
    };
    parameters: {
        /**
         * @description One key per user action (ADR-0019), handled by the edge. A repeat of
         *     the same request returns the stored response with
         *     `Idempotent-Replayed: true`; the same key with a different request
         *     answers `422`; while the first request runs, `409`. Keys expire after
         *     24 hours.
         */
        IdempotencyKey: string;
        /** @description The organization to act in, for credentials that belong to several. */
        Organization: components["schemas"]["Uuid"];
        /** @description The project. A project outside the caller's access answers `404`. */
        Project: components["schemas"]["Uuid"];
        /** @description The project (optional when the API key reaches one project). */
        ProjectHeader: components["schemas"]["Uuid"];
        Tool: components["schemas"]["ToolName"];
        PolicyId: components["schemas"]["Uuid"];
        ApprovalId: components["schemas"]["Uuid"];
        /** @description The `next_cursor` of the previous page. */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /** @description The effect decided (`allow`, `allow_with_limits`, `require_approval`, `deny`). */
        Decision: components["schemas"]["Effect"];
        /** @description The recorded decision (`GET /api/v1/policy-decisions/{decision_id}`). */
        DecisionId: components["schemas"]["Uuid"];
        /** @description The policy that decided (absent when no policy guards the tool). */
        Policy: string;
        /** @description The version of the deciding policy. */
        PolicyVersion: string;
        /** @description The rule that decided (absent when the policy's default applied). */
        PolicyRule: string;
        /** @description `true` when the answer is the stored answer of an earlier call with the same `Idempotency-Key`. */
        IdempotentReplayed: "true";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listToolEndpoints: {
        parameters: {
            query: {
                /** @description The project. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The registered tools. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolEndpointPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getToolEndpoint: {
        parameters: {
            query: {
                /** @description The project. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                tool: components["parameters"]["Tool"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tool endpoint. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolEndpoint"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    putToolEndpoint: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
                /**
                 * @description One key per user action (ADR-0019), handled by the edge. A repeat of
                 *     the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                tool: components["parameters"]["Tool"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolEndpointInput"];
            };
        };
        responses: {
            /** @description The endpoint was replaced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolEndpoint"];
                };
            };
            /** @description The tool was registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolEndpoint"];
                };
            };
            400: components["responses"]["EndpointInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteToolEndpoint: {
        parameters: {
            query: {
                /** @description The project. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
                /**
                 * @description One key per user action (ADR-0019), handled by the edge. A repeat of
                 *     the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                tool: components["parameters"]["Tool"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    listPolicies: {
        parameters: {
            query: {
                /** @description The project. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
                tool?: components["schemas"]["ToolName"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The policies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    createPolicy: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
                /**
                 * @description One key per user action (ADR-0019), handled by the edge. A repeat of
                 *     the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyDocumentInput"];
            };
        };
        responses: {
            /** @description The policy and its first version. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyCreated"];
                };
            };
            400: components["responses"]["PolicyInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["PolicyExists"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    testPolicy: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
                /**
                 * @description One key per user action (ADR-0019), handled by the edge. A repeat of
                 *     the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyTestInput"];
            };
        };
        responses: {
            /** @description What the policy decided. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyTestReport"];
                };
            };
            400: components["responses"]["PolicyTestInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getPolicy: {
        parameters: {
            query: {
                /** @description The project. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                policy_id: components["parameters"]["PolicyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    addPolicyVersion: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
                /**
                 * @description One key per user action (ADR-0019), handled by the edge. A repeat of
                 *     the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                policy_id: components["parameters"]["PolicyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyDocumentInput"];
            };
        };
        responses: {
            /** @description The latest version already decides this. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyVersionAdded"];
                };
            };
            /** @description The new version. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyVersionAdded"];
                };
            };
            400: components["responses"]["PolicyInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getPolicyVersion: {
        parameters: {
            query: {
                /** @description The project. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                policy_id: components["parameters"]["PolicyId"];
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyVersionDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    activatePolicy: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
                /**
                 * @description One key per user action (ADR-0019), handled by the edge. A repeat of
                 *     the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                policy_id: components["parameters"]["PolicyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateInput"];
            };
        };
        responses: {
            /** @description The policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["NotActivatable"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    deactivatePolicy: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
                /**
                 * @description One key per user action (ADR-0019), handled by the edge. A repeat of
                 *     the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                policy_id: components["parameters"]["PolicyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonInput"];
            };
        };
        responses: {
            /** @description The policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            400: components["responses"]["ReasonInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    listApprovals: {
        parameters: {
            query: {
                /** @description The project. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
                status?: components["schemas"]["ApprovalStatus"];
                tool?: components["schemas"]["ToolName"];
                /** @description The `next_cursor` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getApproval: {
        parameters: {
            query: {
                /** @description The project. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    approveApproval: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
                /**
                 * @description One key per user action (ADR-0019), handled by the edge. A repeat of
                 *     the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonInput"];
            };
        };
        responses: {
            /** @description The request, approved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            400: components["responses"]["ReasonInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["ApprovalClosed"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    denyApproval: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
                /**
                 * @description One key per user action (ADR-0019), handled by the edge. A repeat of
                 *     the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonInput"];
            };
        };
        responses: {
            /** @description The request, denied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            400: components["responses"]["ReasonInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["ApprovalClosed"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    listPolicyDecisions: {
        parameters: {
            query: {
                /** @description The project. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
                tool?: components["schemas"]["ToolName"];
                outcome?: components["schemas"]["Outcome"];
                effect?: components["schemas"]["Effect"];
                trace_id?: components["schemas"]["TraceId"];
                approval_id?: components["schemas"]["Uuid"];
                /** @description The `next_cursor` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of decisions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getPolicyDecision: {
        parameters: {
            query: {
                /** @description The project. A project outside the caller's access answers `404`. */
                project_id: components["parameters"]["Project"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                decision_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    invokeTool: {
        parameters: {
            query?: never;
            header?: {
                /** @description The project (optional when the API key reaches one project). */
                "X-AgentTwin-Project"?: components["schemas"]["Uuid"];
                "X-AgentTwin-Agent"?: string;
                "X-AgentTwin-Agent-Version"?: string;
                /** @description Defaults to `production`. */
                "X-AgentTwin-Environment"?: string;
                /** @description The W3C trace context of the agent's run; `trace.calls` counts per trace. */
                traceparent?: string;
                /** @description The trace, when no `traceparent` is sent (they must agree when both are). */
                "X-AgentTwin-Trace-Id"?: components["schemas"]["TraceId"];
                /**
                 * @description Required for a tool registered with `idempotency: required`
                 *     (irreversible tools by default); may instead be the
                 *     `idempotency_key` argument (they must agree when both are sent).
                 */
                "Idempotency-Key"?: string;
                /** @description The token of an approved request for this exact action. */
                "X-AgentTwin-Approval-Token"?: string;
            };
            path: {
                tool: components["parameters"]["Tool"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ToolArguments"];
            };
        };
        responses: {
            400: components["responses"]["InvokeInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["InvokeRefused"];
            404: components["responses"]["ToolNotRegistered"];
            409: components["responses"]["InvokeConflict"];
            413: components["responses"]["InvokePayloadTooLarge"];
            429: components["responses"]["InvokeRateLimited"];
            500: components["responses"]["InvokeInternal"];
            502: components["responses"]["ToolFailed"];
            503: components["responses"]["GatewayUnavailable"];
            504: components["responses"]["ToolTimeout"];
            /** @description The tool's own answer (its status and body). */
            "2XX": {
                headers: {
                    "X-AgentTwin-Decision": components["headers"]["Decision"];
                    "X-AgentTwin-Decision-Id": components["headers"]["DecisionId"];
                    "X-AgentTwin-Policy": components["headers"]["Policy"];
                    "X-AgentTwin-Policy-Version": components["headers"]["PolicyVersion"];
                    "X-AgentTwin-Policy-Rule": components["headers"]["PolicyRule"];
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolAnswer"];
                    "text/plain": components["schemas"]["ToolAnswer"];
                    "application/octet-stream": components["schemas"]["ToolAnswer"];
                };
            };
            /** @description The tool's own answer with another status. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolAnswer"];
                    "text/plain": components["schemas"]["ToolAnswer"];
                    "application/octet-stream": components["schemas"]["ToolAnswer"];
                };
            };
        };
    };
    getGatewayApproval: {
        parameters: {
            query?: never;
            header?: {
                /** @description The project (optional when the API key reaches one project). */
                "X-AgentTwin-Project"?: components["parameters"]["ProjectHeader"];
            };
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    claimApprovalToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description The project (optional when the API key reaches one project). */
                "X-AgentTwin-Project"?: components["parameters"]["ProjectHeader"];
            };
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The token (shown once). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ClaimRefused"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["ApprovalPending"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
}
