/**
 * The runtime gateway's management API as its contract documents it (tool
 * endpoints, policies, approvals, decisions: ADR-0033). The types come from
 * packages/contracts/openapi/runtime-gateway.openapi.yaml (`runtime.gen.ts`,
 * regenerated by `pnpm gen:api`); the contract is checked against the service
 * on every test run (ADR-0021), so what compiles here is what the service does.
 */
import * as contract from "./contract";
import type { components, operations } from "./runtime.gen";

export type RuntimeSchemas = components["schemas"];
export type RuntimeOperation = keyof operations;

/** The query parameters an operation documents. */
export type QueryOf<Op extends RuntimeOperation> = contract.QueryOf<operations, Op>;

/** The JSON body an operation accepts. */
export type BodyOf<Op extends RuntimeOperation> = contract.BodyOf<operations, Op>;

/** The JSON body of one documented response of an operation. */
export type ResponseOf<
  Op extends RuntimeOperation,
  Status extends keyof contract.ResponsesOf<operations, Op>,
> = contract.ResponseOf<operations, Op, Status>;

/** URL query parameters from the documented ones; unset and empty values are left out. */
export function queryOf<Op extends RuntimeOperation>(params: QueryOf<Op>): URLSearchParams {
  return contract.toQuery(params);
}

type S = RuntimeSchemas;

export type Risk = S["Risk"];
export type Effect = S["Effect"];
export type Outcome = S["Outcome"];
export type ApprovalStatus = S["ApprovalStatus"];
export type ToolEndpoint = S["ToolEndpoint"];
export type ToolEndpointPage = S["ToolEndpointPage"];
export type Policy = S["Policy"];
export type PolicyPage = S["PolicyPage"];
export type PolicyDetail = S["PolicyDetail"];
export type VersionSummary = S["VersionSummary"];
export type PolicyVersion = S["PolicyVersion"];
export type PolicyVersionDetail = S["PolicyVersionDetail"];
export type PolicyCreated = S["PolicyCreated"];
export type PolicyVersionAdded = S["PolicyVersionAdded"];
export type PolicyTestInput = S["PolicyTestInput"];
export type PolicyTestReport = S["PolicyTestReport"];
export type PolicyDecision = S["PolicyDecision"];
export type TestResult = S["TestResult"];
export type Threshold = S["Threshold"];
export type Boundary = S["Boundary"];
export type Problem = S["Problem"];
export type Approval = S["Approval"];
export type ApprovalPage = S["ApprovalPage"];
export type ApprovalDetail = S["ApprovalDetail"];
export type Attempt = S["Attempt"];
export type Change = S["Change"];
export type Decision = S["Decision"];
export type DecisionPage = S["DecisionPage"];
export type RecordedDecision = S["RecordedDecision"];
