/**
 * The simulation API as its contract documents it. The types come from
 * packages/contracts/openapi/simulation-service.openapi.yaml (`simulation.gen.ts`,
 * regenerated by `pnpm gen:api`); the contract is checked against the service
 * on every test run (ADR-0021), so what compiles here is what the service does.
 *
 * - Request bodies and query parameters are typed by the contract: a field or
 *   parameter the service would reject does not compile.
 * - The hand-written types in `lib/types.ts` (what the UI reads) must accept
 *   every response the contract allows: `ClientTypesAcceptTheContract` below
 *   does not compile when a response can carry something the UI does not
 *   expect (a `null`, a missing field, another value).
 */
import type {
  ApiErrorBody,
  CaseDetail,
  RunResponse,
  ScenarioDetail,
  ScenarioPage,
  ScenarioSaved,
  ScenarioValidation,
  SimulationCapabilities,
  SimulationPage,
  SimulationRunDetail,
  TwinDetail,
  TwinList,
} from "../types";
import type { components, operations } from "./simulation.gen";

export type SimulationSchemas = components["schemas"];
export type SimulationOperation = keyof operations;

/** The query parameters an operation documents. */
export type QueryOf<Op extends SimulationOperation> = NonNullable<operations[Op]["parameters"]["query"]>;

/** The JSON body an operation accepts. */
export type BodyOf<Op extends SimulationOperation> =
  NonNullable<operations[Op]["requestBody"]> extends { content: { "application/json": infer B } } ? B : never;

/** The JSON body of one documented response of an operation. */
export type ResponseOf<
  Op extends SimulationOperation,
  Status extends keyof operations[Op]["responses"],
> = operations[Op]["responses"][Status] extends { content: { "application/json": infer B } }
  ? B
  : { missing: "this response has no JSON body" };

/** URL query parameters from the documented ones; unset and empty values are left out. */
export function queryOf<Op extends SimulationOperation>(params: QueryOf<Op>): URLSearchParams {
  const out = new URLSearchParams();
  for (const [key, value] of Object.entries(params as Record<string, unknown>)) {
    if (value === undefined || value === null || value === "") continue;
    out.set(key, String(value));
  }
  return out;
}

// ------------------------------------------------------------------ checks

/**
 * Compiles only when a client type that reads `Server` accepts every value of
 * it; otherwise the compiler reports the first field that disagrees ("does
 * not satisfy the constraint", then the path to the field).
 */
type Accepts<Client, Server extends Client> = Server;

/** Each hand-written response type accepts the documented response of the operation that returns it. */
export type ClientTypesAcceptTheContract = [
  Accepts<SimulationPage, ResponseOf<"listSimulations", 200>>,
  Accepts<RunResponse, ResponseOf<"startSimulation", 202>>,
  Accepts<SimulationRunDetail, ResponseOf<"getSimulation", 200>>,
  Accepts<RunResponse, ResponseOf<"cancelSimulation", 202>>,
  Accepts<RunResponse, ResponseOf<"cancelSimulation", 200>>,
  Accepts<CaseDetail, ResponseOf<"getSimulationCase", 200>>,
  Accepts<SimulationCapabilities, ResponseOf<"getSimulationCapabilities", 200>>,
  Accepts<ScenarioPage, ResponseOf<"listScenarios", 200>>,
  Accepts<ScenarioDetail, ResponseOf<"getScenario", 200>>,
  Accepts<ScenarioValidation, ResponseOf<"validateScenario", 200>>,
  Accepts<ScenarioSaved, ResponseOf<"saveScenario", 201>>,
  Accepts<ScenarioSaved, ResponseOf<"saveScenario", 200>>,
  Accepts<TwinList, ResponseOf<"listTwins", 200>>,
  Accepts<TwinDetail, ResponseOf<"getTwin", 200>>,
  Accepts<ApiErrorBody, SimulationSchemas["Error"]>,
];
