/**
 * The simulation API as its contract documents it. The types come from
 * packages/contracts/openapi/simulation-service.openapi.yaml (`simulation.gen.ts`,
 * regenerated by `pnpm gen:api`); the contract is checked against the service
 * on every test run (ADR-0021), so what compiles here is what the service does.
 *
 * - Request bodies and query parameters are typed by the contract: a field or
 *   parameter the service would reject does not compile.
 * - The hand-written types in `lib/types.ts` (what the UI reads) must accept
 *   every response the contract allows: `ClientTypesAcceptTheContract` below
 *   does not compile when a response can carry something the UI does not
 *   expect (a `null`, a missing field, another value).
 */
import type {
  ApiErrorBody,
  CaseDetail,
  RunResponse,
  ScenarioDetail,
  ScenarioPage,
  ScenarioSaved,
  ScenarioValidation,
  SimulationCapabilities,
  SimulationPage,
  SimulationRunDetail,
  TwinDetail,
  TwinList,
} from "../types";
import * as contract from "./contract";
import type { Accepts } from "./contract";
import type { components, operations } from "./simulation.gen";

export type SimulationSchemas = components["schemas"];
export type SimulationOperation = keyof operations;

/** The query parameters an operation documents. */
export type QueryOf<Op extends SimulationOperation> = contract.QueryOf<operations, Op>;

/** The JSON body an operation accepts. */
export type BodyOf<Op extends SimulationOperation> = contract.BodyOf<operations, Op>;

/** The JSON body of one documented response of an operation. */
export type ResponseOf<
  Op extends SimulationOperation,
  Status extends keyof contract.ResponsesOf<operations, Op>,
> = contract.ResponseOf<operations, Op, Status>;

/** URL query parameters from the documented ones; unset and empty values are left out. */
export function queryOf<Op extends SimulationOperation>(params: QueryOf<Op>): URLSearchParams {
  return contract.toQuery(params);
}

// ------------------------------------------------------------------ checks

/** Each hand-written response type accepts the documented response of the operation that returns it. */
export type ClientTypesAcceptTheContract = [
  Accepts<SimulationPage, ResponseOf<"listSimulations", 200>>,
  Accepts<RunResponse, ResponseOf<"startSimulation", 202>>,
  Accepts<SimulationRunDetail, ResponseOf<"getSimulation", 200>>,
  Accepts<RunResponse, ResponseOf<"cancelSimulation", 202>>,
  Accepts<RunResponse, ResponseOf<"cancelSimulation", 200>>,
  Accepts<CaseDetail, ResponseOf<"getSimulationCase", 200>>,
  Accepts<SimulationCapabilities, ResponseOf<"getSimulationCapabilities", 200>>,
  Accepts<ScenarioPage, ResponseOf<"listScenarios", 200>>,
  Accepts<ScenarioDetail, ResponseOf<"getScenario", 200>>,
  Accepts<ScenarioValidation, ResponseOf<"validateScenario", 200>>,
  Accepts<ScenarioSaved, ResponseOf<"saveScenario", 201>>,
  Accepts<ScenarioSaved, ResponseOf<"saveScenario", 200>>,
  Accepts<TwinList, ResponseOf<"listTwins", 200>>,
  Accepts<TwinDetail, ResponseOf<"getTwin", 200>>,
  Accepts<ApiErrorBody, SimulationSchemas["Error"]>,
];
