/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/twins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List twins
         * @description The latest version of every twin in the caller's projects (at most 500).
         */
        get: operations["listTwins"];
        put?: never;
        /**
         * Register a twin definition
         * @description Stores a `TwinDefinition` document as a new version of the named twin
         *     when its content changed (`201`); identical content answers the latest
         *     version (`200`). Invalid documents answer `400 TWIN_INVALID` with
         *     `details.problems`.
         */
        post: operations["registerTwin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/twins/{twin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a twin version
         * @description One twin version with its tools, its document (planted canary secrets
         *     are masked), the document as YAML and the list of all versions of the
         *     twin.
         */
        get: operations["getTwin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate a scenario without saving it
         * @description Checks a scenario document on its own (schema, evaluator parameters)
         *     and against the latest version of the twin it names. Problems of the
         *     document are part of a `200` answer (`valid: false`), not an error.
         *     Needs read access to the project.
         */
        post: operations["validateScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List scenarios
         * @description Scenarios with their latest version, ordered by name.
         */
        get: operations["listScenarios"];
        put?: never;
        /**
         * Save a scenario version
         * @description Saving is by name within the project: a new name creates a scenario, an
         *     existing name adds a version to it (and restores it when archived).
         *     Content equal to the latest version answers `200` without a new
         *     version. An invalid document answers `400 SCENARIO_INVALID` with
         *     `details.problems` and `details.warnings`.
         */
        post: operations["saveScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a scenario version
         * @description A scenario with the document of one version (default the latest) and its version list.
         */
        get: operations["getScenario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a scenario
         * @description Archived scenarios are hidden from lists and never selected by runs.
         *     Saving a version under the same name restores the scenario.
         */
        post: operations["archiveScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What this deployment can simulate
         * @description Runnable agents, fault and expectation types, evaluator versions and limits.
         */
        get: operations["getSimulationCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List simulation runs
         * @description Runs, newest first.
         */
        get: operations["listSimulations"];
        put?: never;
        /**
         * Start a simulation run
         * @description Queues a run of one agent version against the selected scenarios (by
         *     name, by tag, or every scenario that applies to the agent) and answers
         *     `202` with the pinned versions and seeds. A worker executes the run
         *     (ADR-0017); poll `GET /api/v1/simulations/{run_id}`.
         *
         *     `400` codes: `AGENT_NOT_RUNNABLE` (no endpoint is configured for the
         *     agent; `details.runnable`), `AGENT_VERSION_NOT_FOUND`,
         *     `SCENARIO_NOT_FOUND` (`details.missing`), `NO_SCENARIOS`,
         *     `TOO_MANY_SCENARIOS`, `SCENARIO_INVALID` (a scenario cannot run against
         *     its twin; `details.scenarios`), `INVALID_PARAMETER`, `INVALID_REQUEST`.
         */
        post: operations["startSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a simulation run
         * @description The run with its pinning, its cases and its lifecycle transitions.
         */
        get: operations["getSimulation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/{run_id}/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one case of a run
         * @description The case with its verdict, expectation results, state diff and the
         *     agent's answer; the scenario document it ran; every step the twin
         *     recorded; and the twin state before and after. Planted canary values
         *     are replaced by `[REDACTED:canary]` wherever they appear.
         */
        get: operations["getSimulationCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request cancellation of a run
         * @description Cancellation is a request: `202` while a worker stops the run at its
         *     next checkpoint (within about a second during an agent call); `200`
         *     when the run is already final — or became final at once because it was
         *     still queued.
         */
        post: operations["cancelSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/twin/v1/tools/{tool}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Call a tool of the case's twin
         * @description The request body is the tool's arguments object. The reply — status,
         *     headers and body — is the twin's: what the tool's handler or an
         *     injected fault answers (ADR-0016), so it can be any status and, under
         *     wire faults, a dropped connection, a partial body or malformed JSON.
         *     The twin records every call. The endpoint's own refusals use the error
         *     envelope: `401 TWIN_CREDENTIAL_REQUIRED` / `TWIN_CREDENTIAL_INVALID`,
         *     `400 INVALID_TOOL_NAME` / `INVALID_JSON` / `INVALID_ARGUMENTS`,
         *     `409 RUN_CANCELLED` / `CASE_CLOSED` / `CALL_LIMIT_EXCEEDED`, `413`.
         */
        post: operations["callTwinTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/twin/v1/kb/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the case's knowledge base
         * @description Retrieval over the twin's documents and the scenario's planted
         *     documents. The results carry no trust labels: retrieved content is
         *     untrusted input to the agent. Every search is recorded as a step.
         */
        get: operations["searchTwinKnowledgeBase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    agentRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agent adapter contract: POST {agent endpoint}/run
         * @description The simulation worker calls the agent under test once per case
         *     (ADR-0011). The agent calls the twin's tools at `tools_base_url` with
         *     `tool_headers` (the case's capability token) and answers when the
         *     conversation ends. Tool calls are recorded by the twin, not taken from
         *     the answer. Any status other than `200`, a body that is not a JSON
         *     object, a timeout or an unreachable agent decide the case's verdict
         *     (`agent_result.kind`).
         */
        post: operations["runAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /** Format: date-time */
        Timestamp: string;
        /** @description SHA-256 (hex) of the document's canonical JSON form. */
        SpecHash: string;
        /** @enum {string} */
        Severity: "critical" | "high" | "medium" | "low";
        /** @enum {string} */
        RunStatus: "QUEUED" | "PREPARING" | "RUNNING" | "EVALUATING" | "COMPLETED" | "FAILED" | "CANCELLED";
        /** @enum {string} */
        CaseStatus: "PENDING" | "RUNNING" | "PASSED" | "FAILED" | "ERRORED" | "CANCELLED";
        /**
         * @description `BASELINE` / `CANDIDATE` when the run is one side of a release evaluation.
         * @enum {string}
         */
        Side: "SINGLE" | "BASELINE" | "CANDIDATE";
        Error: {
            error: {
                /** @description Stable, machine-readable (e.g. `SCENARIO_INVALID`). */
                code: string;
                /** @description For people; may change. */
                message: string;
                /** @description Equals the `X-Request-Id` response header. */
                request_id: string;
                /** @description Code-specific context (field names, problems, missing names). */
                details?: Record<string, unknown>;
            };
        };
        /** @description Exactly one of `yaml` and `document`. */
        DocumentRequest: {
            project_id: components["schemas"]["Uuid"];
            /**
             * @description The document as YAML text: plain data only (no anchors, aliases or
             *     tags), at most 512 KiB, duplicate keys rejected.
             */
            yaml?: string;
            /** @description The document as a JSON object. */
            document?: Record<string, unknown>;
        } & (unknown | unknown);
        TwinSummary: {
            id: components["schemas"]["Uuid"];
            organization_id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            name: string;
            version: number;
            spec_hash: components["schemas"]["SpecHash"];
            tool_count: number;
            description: string | null;
            /** @description The actor that stored this version (e.g. `user:…`, `apikey:…`). */
            created_by: string;
            created_at: components["schemas"]["Timestamp"];
        };
        TwinTool: {
            name: string;
            description: string;
            /** @enum {string} */
            risk: "READ" | "WRITE_REVERSIBLE" | "WRITE_IRREVERSIBLE" | "EXECUTE" | "ADMIN";
            /** @enum {string} */
            handler: "read" | "mutate" | "static" | "echo" | "recorded" | "custom";
            /** @description A successful call changes the twin's state. */
            mutates: boolean;
            /** @description The argument that carries the idempotency key, or `header:<name>`. */
            idempotency: string | null;
            tenant_scoped: boolean;
        };
        Twin: components["schemas"]["TwinSummary"] & {
            tools: components["schemas"]["TwinTool"][];
        };
        TwinDetail: components["schemas"]["Twin"] & {
            /** @description The state field that holds a record's tenant. */
            tenant_key: string | null;
        };
        TwinVersion: {
            id: components["schemas"]["Uuid"];
            version: number;
            spec_hash: components["schemas"]["SpecHash"];
            tool_count: number;
            created_by: string;
            created_at: components["schemas"]["Timestamp"];
        };
        RegisterTwinResponse: {
            twin: components["schemas"]["Twin"];
            created: boolean;
        };
        TwinList: {
            items: components["schemas"]["TwinSummary"][];
        };
        TwinDetailResponse: {
            twin: components["schemas"]["TwinDetail"];
            /** @description The `TwinDefinition` document (twin.v1), canary secrets masked. */
            document: components["schemas"]["TwinV1"];
            /** @description The document as YAML, in reading order. */
            yaml: string;
            /** @description All versions of the twin, newest first. */
            versions: components["schemas"]["TwinVersion"][];
        };
        Scenario: {
            id: components["schemas"]["Uuid"];
            organization_id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            name: string;
            /** @description The agent the scenario is for (`null`: every agent). */
            agent: string | null;
            /** @description The twin the scenario runs against. */
            twin: string | null;
            severity: components["schemas"]["Severity"];
            tags: string[];
            /** @enum {string} */
            source: "manual" | "production_regression" | "generated" | "policy_derived" | "imported" | "production_replay";
            latest_version: number;
            archived: boolean;
            created_by: string;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
            /** @description The version this response describes (present with the version). */
            version_id?: components["schemas"]["Uuid"];
            spec_hash?: components["schemas"]["SpecHash"];
            /** @description The description of the latest version (lists only; absent when empty). */
            description?: string;
            /** @description Lists only. */
            expectation_count?: number;
            /** @description Lists only. */
            fault_count?: number;
        };
        ScenarioVersion: {
            id: components["schemas"]["Uuid"];
            version: number;
            spec_hash: components["schemas"]["SpecHash"];
            created_by: string;
            created_at: components["schemas"]["Timestamp"];
        };
        ScenarioValidation: {
            valid: boolean;
            /** @description What makes the document invalid, as `path: message`. */
            problems: string[];
            /** @description Accepted but probably not what was meant. */
            warnings: string[];
            /** @description `null` when the body is not a document at all. */
            spec_hash: components["schemas"]["SpecHash"] | null;
            /** @description The twin the scenario was checked against. */
            twin: components["schemas"]["TwinSummary"] | null;
        };
        SaveScenarioResponse: {
            scenario: components["schemas"]["Scenario"];
            version: number;
            created: boolean;
            warnings: string[];
        };
        ScenarioPage: {
            items: components["schemas"]["Scenario"][];
            next_cursor: string | null;
        };
        ScenarioDetail: {
            scenario: components["schemas"]["Scenario"];
            version: number;
            version_created_by: string;
            version_created_at: components["schemas"]["Timestamp"];
            /** @description The scenario document (scenario.v1) of this version. */
            document: components["schemas"]["ScenarioV1"];
            /** @description The document as YAML, in reading order (ADR-0020). */
            yaml: string;
            /** @description All versions, newest first. */
            versions: components["schemas"]["ScenarioVersion"][];
        };
        ScenarioResponse: {
            scenario: components["schemas"]["Scenario"];
        };
        Capabilities: {
            /** @description Agents this deployment can run (an endpoint is configured). */
            agents: string[];
            fault_types: ("timeout_before_mutation" | "timeout_after_mutation" | "http_429" | "http_500" | "http_503" | "malformed_json" | "semantic_bad_response" | "delay" | "dropped_connection" | "partial_response" | "stale_response" | "duplicate_response" | "auth_denied" | "rate_limit" | "transient_unavailable" | "permanent_unavailable" | "inconsistent_state" | "success_without_mutation" | "message_duplication" | "non_retryable_error")[];
            expectation_types: string[];
            /** @description Evaluator name → version. */
            evaluators: {
                [key: string]: string;
            };
            /** @description The twin engine version (e.g. `twin-engine/1.0.0`). */
            engine: string;
            limits: {
                max_cases: number;
                max_calls_per_case: number;
                case_timeout_seconds: number;
                max_fault_delay_ms: number;
            };
        };
        StartSimulationRequest: {
            project_id: components["schemas"]["Uuid"];
            agent: string;
            /** @description A registered version of the agent. */
            agent_version: string;
            /** @description Scenario names (default every scenario that applies to the agent). */
            scenarios?: string[] | null;
            /** @description Scenarios with any of these tags. */
            tags?: string[] | null;
            /** @description The run seed (default random); it is pinned either way. */
            seed?: number | null;
            /**
             * Format: uuid
             * @description The release evaluation this run belongs to.
             */
            eval_run_id?: string | null;
            side?: components["schemas"]["Side"];
            release_id?: string | null;
        };
        Run: {
            id: components["schemas"]["Uuid"];
            organization_id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            agent_name: string;
            agent_version: string;
            /** Format: uuid */
            agent_version_id: string | null;
            side: components["schemas"]["Side"];
            /** Format: uuid */
            eval_run_id: string | null;
            release_id: string | null;
            status: components["schemas"]["RunStatus"];
            requested_by: string;
            cancel_requested: boolean;
            /** @description Worker attempts (a run whose worker died is retried, at most 3 times). */
            attempts: number;
            case_count: number;
            passed: number;
            failed: number;
            errored: number;
            cancelled: number;
            /** @description Failed cases of critical-severity scenarios (what blocks a release). */
            critical_failures: number;
            /** @description Why the run failed, when it did. */
            error: string | null;
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            finished_at: string | null;
            updated_at: components["schemas"]["Timestamp"];
            /** @description passed + failed + errored + cancelled. */
            finished_cases: number;
        };
        PinnedScenario: {
            scenario: string;
            scenario_version_id: components["schemas"]["Uuid"];
            spec_hash: components["schemas"]["SpecHash"];
            twin: string;
            twin_definition_id: components["schemas"]["Uuid"];
            twin_version: number;
            twin_spec_hash: components["schemas"]["SpecHash"];
            seed: number;
        };
        /** @description Everything needed to reproduce the run. */
        Pinning: {
            correlation_id: string;
            seed: number;
            agent: {
                name: string;
                version: string;
                /** Format: uuid */
                version_id: string | null;
                manifest_sha256: string | null;
                prompt_sha256: string | null;
                model_provider: string | null;
                model_name: string | null;
                commit_sha: string | null;
            };
            scenarios: components["schemas"]["PinnedScenario"][];
            evaluators: {
                [key: string]: string;
            };
            engine: string;
            selection: {
                scenarios: string[] | null;
                tags: string[] | null;
            };
        };
        PinnedRun: components["schemas"]["Run"] & {
            pinning: components["schemas"]["Pinning"];
        };
        QueuedCase: {
            id: components["schemas"]["Uuid"];
            position: number;
            scenario_id: components["schemas"]["Uuid"];
            scenario_name: string;
            severity: components["schemas"]["Severity"];
            seed: number;
            tenant: string | null;
        };
        StartSimulationResponse: {
            run: components["schemas"]["PinnedRun"];
            cases: components["schemas"]["QueuedCase"][];
        };
        RunPage: {
            items: components["schemas"]["Run"][];
            next_cursor: string | null;
        };
        RunResponse: {
            run: components["schemas"]["Run"];
        };
        Transition: {
            seq: number;
            from_status: components["schemas"]["RunStatus"] | null;
            to_status: components["schemas"]["RunStatus"];
            reason: string | null;
            at: components["schemas"]["Timestamp"];
        };
        CaseSummary: {
            id: components["schemas"]["Uuid"];
            run_id: components["schemas"]["Uuid"];
            position: number;
            scenario_id: components["schemas"]["Uuid"];
            scenario_version_id: components["schemas"]["Uuid"];
            scenario_name: string;
            severity: components["schemas"]["Severity"];
            twin_definition_id: components["schemas"]["Uuid"];
            status: components["schemas"]["CaseStatus"];
            seed: number;
            tenant: string | null;
            /** @description Tool calls the twin recorded (retrievals are not counted). */
            call_count: number;
            /** @description The agent's trace of this case, when it reported one. */
            trace_id: string | null;
            /** @description Why the case ended as it did. */
            reason: string | null;
            error: string | null;
            latency_ms: number | null;
            /**
             * @description Delivery of the verified outcome to the trace service.
             * @enum {string}
             */
            outcome_status: "none" | "pending" | "posted" | "failed";
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            finished_at: string | null;
            /** @description Labels of the failed expectations. */
            labels: string[];
            /** @description Fraction of evaluated expectations that passed. */
            score: number | null;
        };
        RunDetail: {
            run: components["schemas"]["PinnedRun"];
            cases: components["schemas"]["CaseSummary"][];
            transitions: components["schemas"]["Transition"][];
        };
        /**
         * @description `FAILED` if any expectation failed; otherwise `ERRORED` if one could not
         *     be evaluated, a critical expectation was skipped, nothing was evaluated
         *     or there are no expectations; otherwise `PASSED`.
         */
        Verdict: {
            /** @enum {string} */
            status: "PASSED" | "FAILED" | "ERRORED";
            reason: string;
            passed: number;
            failed: number;
            errored: number;
            skipped: number;
            /** @description Failed critical expectations of this case. */
            critical_failures: number;
            score: number | null;
            labels: string[];
        };
        Evidence: {
            /** @enum {string} */
            kind: "tool_call" | "state" | "output" | "agent" | "config";
            detail: string;
            /** @description What the evidence points at (e.g. `tool_call:3`). */
            ref?: string;
            /** @description The expected value, when there is one. */
            expected?: unknown;
            /** @description The observed value, when there is one. */
            actual?: unknown;
        };
        ExpectationResult: {
            /** @enum {string} */
            status: "PASS" | "FAIL" | "ERROR" | "SKIPPED";
            reason: string;
            evaluator: string;
            evaluator_version: string;
            score: number | null;
            label: string | null;
            critical: boolean;
            /** @description Which expectation of the scenario this result is for. */
            expectation: {
                /** @description The expectation's `id`, or `e<n>` (its position, from 1) when it has none. */
                id: string;
                type: string;
                critical: boolean;
                description?: string;
                category?: string;
                tool?: string;
                path?: string;
            };
            evidence: components["schemas"]["Evidence"][];
        };
        StateChange: {
            /** @enum {string} */
            op: "added" | "removed" | "changed";
            /** @description A JSONPath-like location (`$` for the root). */
            path: string;
            /** @description The value before (removed, changed). */
            before?: unknown;
            /** @description The value after (added, changed). */
            after?: unknown;
        };
        /** @description What was kept of the agent's answer (bounded, never credentials). */
        AgentResult: {
            /** @enum {string} */
            kind: "ok" | "timeout" | "unreachable" | "http_error" | "invalid_response";
            http_status: number | null;
            elapsed_ms: number;
            /** @description Why the call did not succeed. */
            error?: string;
            output?: string;
            trace_id?: string;
            status?: string;
            agent_version?: string;
            model?: string;
            model_kind?: string;
            steps?: number;
            claimed_outcome?: string;
            business_outcome?: string | null;
            /** @description The agent's own account of its tool calls (the twin's records are the evidence). */
            tool_calls?: Record<string, unknown>[];
            agent_error?: {
                code: string;
                message: string;
            };
        };
        CaseResult: components["schemas"]["CaseSummary"] & {
            verdict: components["schemas"]["Verdict"] | null;
            results: components["schemas"]["ExpectationResult"][];
            /** @description What changed in the twin's state during the case. */
            state_diff: components["schemas"]["StateChange"][];
            agent_result: components["schemas"]["AgentResult"] | null;
        };
        /** @description One tool call as the twin observed it. */
        ToolCallRecord: {
            seq: number;
            /** @description The n-th call of this tool in the case. */
            call_number: number;
            tool: string;
            arguments: Record<string, unknown>;
            /** @description `0` when no response reached the caller. */
            http_status: number;
            /** @enum {string} */
            status: "ok" | "rate_limited" | "denied" | "not_found" | "unknown_tool" | "timeout" | "invalid" | "error" | "dropped" | "partial" | "malformed";
            error_code: string | null;
            /** @description The reply body the agent received (`null` when none). */
            response: unknown;
            risk: string | null;
            /** @description The injected fault type, if any. */
            fault: string | null;
            mutated: boolean;
            expects_mutation: boolean;
            /** @description Answered from the idempotency record, without a second effect. */
            replayed: boolean;
            effect_key: string | null;
            cross_tenant: string | null;
            policy_violation: string | null;
            redelivered: boolean;
            changes: components["schemas"]["StateChange"][];
            delay_ms: number;
        };
        RetrievalRecord: {
            seq: number;
            /** @constant */
            kind: "retrieval";
            query: string;
            limit: number;
            documents: {
                id: string;
                trusted: boolean;
            }[];
        };
        Step: {
            seq: number;
            /** @enum {string} */
            kind: "tool_call" | "retrieval";
            tool: string | null;
            latency_ms: number | null;
            created_at: components["schemas"]["Timestamp"];
            record: components["schemas"]["ToolCallRecord"] | components["schemas"]["RetrievalRecord"];
        };
        CaseDetail: {
            case: components["schemas"]["CaseResult"];
            scenario: {
                /** @description The scenario version the case ran. */
                document: components["schemas"]["ScenarioV1"];
                /** @description The scenario's fault rules (its `spec.faults`). */
                faults: components["schemas"]["ScenarioV1Fault"][];
            };
            twin: {
                id: components["schemas"]["Uuid"];
                name: string;
                version: number;
                spec_hash: components["schemas"]["SpecHash"];
            } | null;
            steps: components["schemas"]["Step"][];
            state: {
                /** @description The twin state the case started from. */
                initial: Record<string, unknown> | null;
                /** @description The twin state when the case ended. */
                final: Record<string, unknown> | null;
            };
        };
        KnowledgeBaseResults: {
            documents: {
                id: string;
                title: string;
                text: string;
            }[];
        };
        AgentRunRequest: {
            /** @description The customer's message. */
            input: string;
            /** @description The version to run. */
            agent_version: string;
            /** @description `sim-<case id>`. */
            session_id: string;
            /**
             * Format: uri
             * @description The twin endpoint; tools are `POST {tools_base_url}/tools/{tool}`.
             */
            tools_base_url: string;
            /** @description Headers to send with every tool call (the case's capability token). */
            tool_headers: {
                [key: string]: string;
            };
            run_context: {
                /** @constant */
                source: "simulation";
                simulation_run_id: components["schemas"]["Uuid"];
                scenario_id: components["schemas"]["Uuid"];
                scenario_name: string;
                case_id: components["schemas"]["Uuid"];
                release_id: string | null;
            };
            /** @description The tenant the case runs as (from the scenario). */
            tenant?: string;
            /** @description The customer the conversation is with (from the scenario). */
            customer_id?: string;
            /** @description Other values of the scenario's `input.context`. */
            context?: Record<string, unknown>;
        };
        /**
         * @description Every field is optional for the worker; what is present is kept for
         *     display and outcome checks (bounded).
         */
        AgentRunResponse: {
            /** @description The agent's final answer to the customer. */
            output?: string;
            /** @description The agent's trace of the conversation (links the case to it). */
            trace_id?: string;
            /** @description How the conversation ended (e.g. `completed`, `step_limit`). */
            status?: string;
            agent_version?: string;
            model?: string;
            model_kind?: string;
            steps?: number;
            /** @description What the agent says it achieved (checked against the twin's state). */
            claimed_outcome?: string;
            business_outcome?: string | null;
            tool_calls?: Record<string, unknown>[];
        };
        AgentError: {
            error?: {
                code?: string;
                message?: string;
            };
        };
        /** AgentTwin TwinDefinition v1 (declarative stateful tool twin) */
        TwinV1: {
            /** @constant */
            apiVersion: "agenttwin.dev/v1";
            /** @constant */
            kind: "TwinDefinition";
            metadata: {
                name: string;
                description?: string;
                /** @enum {unknown} */
                source?: "declarative" | "openapi" | "mcp" | "recorded" | "custom";
            };
            spec: {
                /** @description Planted secret values that must never appear in agent output or tool arguments. */
                secrets?: string[];
                /** @description Entity field holding the owning tenant (cross-tenant detection). */
                tenantKey?: string;
                tools: {
                    [key: string]: components["schemas"]["TwinV1Tool"];
                };
                /** @description The twin's default state; a scenario's spec.state is applied on top as a JSON Merge Patch (RFC 7396). */
                initialState?: Record<string, unknown>;
                retrieval?: {
                    /** @description State path of the knowledge-base documents served at /kb/search (default: kb). */
                    statePath?: string;
                };
            };
        };
        TwinV1Condition: {
            path: string;
            exists?: boolean;
            equals?: unknown;
            notEquals?: unknown;
            in?: unknown[];
            gte?: unknown;
            lte?: unknown;
            gt?: unknown;
            lt?: unknown;
            error?: components["schemas"]["TwinV1Error"];
        };
        TwinV1Effect: {
            /** @enum {unknown} */
            op: "set" | "increment" | "decrement" | "append" | "delete" | "merge";
            path: string;
            /** @description Value for set/append/merge; strings may be templates. */
            value?: unknown;
            /** @description Amount for increment/decrement (default 1); may be a template such as "{amount}". */
            by?: number | string;
        };
        TwinV1Tool: {
            description?: string;
            /** @enum {unknown} */
            risk?: "READ" | "WRITE_REVERSIBLE" | "WRITE_IRREVERSIBLE" | "EXECUTE" | "ADMIN";
            inputSchema?: Record<string, unknown>;
            outputSchema?: Record<string, unknown>;
            idempotency?: {
                argument?: string;
                header?: string;
            };
            /** @description Template identifying the logical side effect (duplicate detection), e.g. 'refund:{order_id}'. */
            effectKey?: string;
            /** @description Template path of the entity whose tenant is checked, e.g. 'customers.{customer_id}'. */
            tenantPath?: string;
            handler: {
                /** @enum {unknown} */
                kind: "read" | "mutate" | "static" | "echo" | "recorded" | "custom";
                path?: string;
                notFound?: components["schemas"]["TwinV1Error"];
                preconditions?: components["schemas"]["TwinV1Condition"][];
                effects?: components["schemas"]["TwinV1Effect"][];
                response?: Record<string, unknown>;
                fixtures?: components["schemas"]["TwinV1Fixture"][];
                adapter?: string;
            };
        };
        TwinV1Fixture: {
            /** @description Arguments that must be present with these values. */
            match?: Record<string, unknown>;
            status?: number;
            response?: unknown;
            error?: components["schemas"]["TwinV1Error"];
        };
        TwinV1Error: {
            status: number;
            code: string;
            message?: string;
        };
        /** AgentTwin Scenario v1 */
        ScenarioV1: {
            /** @constant */
            apiVersion: "agenttwin.dev/v1";
            /** @constant */
            kind: "Scenario";
            metadata: {
                name: string;
                /** @enum {unknown} */
                severity: "critical" | "high" | "medium" | "low";
                tags?: string[];
                description?: string;
                owner?: string;
                /** @enum {unknown} */
                source?: "manual" | "production_regression" | "generated" | "policy_derived" | "imported" | "production_replay";
                sourceTraceId?: string;
                generated?: {
                    by?: string;
                    evidence?: string[];
                    reviewed?: boolean;
                };
            };
            spec: {
                agent?: string;
                twin?: string;
                input: {
                    message: string;
                    context?: Record<string, unknown>;
                    documents?: {
                        id: string;
                        content: string;
                        /** @default false */
                        trusted?: boolean;
                    }[];
                };
                /** @description Initial tool-twin state (isolated per run). */
                state?: Record<string, unknown>;
                allowedTools?: string[];
                covers?: string[];
                faults?: components["schemas"]["ScenarioV1Fault"][];
                expectations: components["schemas"]["ScenarioV1Expectation"][];
                seed?: number;
                /**
                 * @default strict
                 * @enum {unknown}
                 */
                simulationMode?: "strict" | "approximate";
                timeoutSeconds?: number;
            };
        };
        ScenarioV1Fault: {
            target: string;
            when?: {
                callNumber?: number;
                callNumbers?: number[];
                everyCall?: boolean;
                firstN?: number;
                argsMatch?: Record<string, unknown>;
                probability?: number;
            };
            behavior: {
                /** @enum {unknown} */
                type: "timeout_before_mutation" | "timeout_after_mutation" | "http_429" | "http_500" | "http_503" | "malformed_json" | "semantic_bad_response" | "delay" | "dropped_connection" | "partial_response" | "stale_response" | "duplicate_response" | "auth_denied" | "rate_limit" | "transient_unavailable" | "permanent_unavailable" | "inconsistent_state" | "success_without_mutation" | "message_duplication" | "non_retryable_error";
                delayMs?: number;
                retryAfterSeconds?: number;
                body?: unknown;
                message?: string;
            };
        };
        ScenarioV1Comparator: {
            equals?: unknown;
            notEquals?: unknown;
            in?: unknown[];
            exists?: boolean;
            gte?: number;
            lte?: number;
            gt?: number;
            lt?: number;
            matches?: string;
        };
        ScenarioV1ExpectationBase: {
            id?: string;
            critical?: boolean;
            description?: string;
            category?: string;
        };
        ScenarioV1Expectation: {
            /** @enum {unknown} */
            type: "state" | "stateUnchanged" | "finalOutcome" | "outcomeVerified" | "toolCalled" | "toolNotCalled" | "maxToolCalls" | "toolArgs" | "toolStatus" | "order" | "maxRetries" | "maxSteps" | "maxLatencyMs" | "maxCostUsd" | "requiredEscalation" | "noPolicyViolation" | "noIrreversibleAction" | "approvalRequired" | "noDuplicateSideEffect" | "outputContains" | "outputNotContains" | "outputRegex" | "outputJsonSchema" | "outputJsonPath" | "noSecretDisclosure" | "noCrossTenantAccess" | "semantic";
            id?: string;
            critical?: boolean;
            description?: string;
            category?: string;
            path?: string;
            tool?: string;
            value?: unknown;
            equals?: unknown;
            notEquals?: unknown;
            in?: unknown[];
            exists?: boolean;
            gte?: number;
            lte?: number;
            gt?: number;
            lt?: number;
            matches?: string;
            min?: number;
            call?: number;
            status?: number;
            mustCall?: string[];
            before?: string[];
            pattern?: string;
            schema?: Record<string, unknown>;
            secrets?: string[];
            rubric?: string;
            threshold?: number;
            judge?: string;
        } & (unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown);
    };
    responses: {
        /**
         * @description The request is invalid. `INVALID_REQUEST` (body fields; `details.errors`),
         *     `INVALID_PARAMETER` (`details.field`), `INVALID_JSON`, `EMPTY_BODY`,
         *     `INVALID_CURSOR`, `INVALID_IDEMPOTENCY_KEY` or an operation-specific code.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid credential (`UNAUTHENTICATED`). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The credential lacks the permission (`FORBIDDEN`; `details.required_permission`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource does not exist or is outside the caller's projects (`NOT_FOUND`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The first request with this `Idempotency-Key` is still running (`IDEMPOTENCY_IN_PROGRESS`). */
        IdempotencyInProgress: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request body is too large (`PAYLOAD_TOO_LARGE`). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The body is not `application/json` (`UNSUPPORTED_MEDIA_TYPE`). */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The `Idempotency-Key` was used for a different request (`IDEMPOTENCY_KEY_REUSED`). */
        IdempotencyKeyReused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests (`RATE_LIMITED`). */
        RateLimited: {
            headers: {
                /** @description Seconds to wait. */
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description An unexpected error (`INTERNAL`); quote the `request_id`. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The simulation service is not reachable from the control plane (`UPSTREAM_UNAVAILABLE`). */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description A dependency is unavailable (`UNAVAILABLE`), or the simulation service
         *     is not configured on this control plane (`SERVICE_NOT_CONFIGURED`).
         */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The case token is missing (`TWIN_CREDENTIAL_REQUIRED`), unknown, or its case is closed (`TWIN_CREDENTIAL_INVALID`). */
        TwinCredential: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The run was cancelled (`RUN_CANCELLED`), the case is not running (`CASE_CLOSED`) or it reached its call limit (`CALL_LIMIT_EXCEEDED`). */
        CaseNotRunning: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description One key per user action (ADR-0019). A repeat of the same request
         *     returns the stored response with `Idempotent-Replayed: true`; the same
         *     key with a different request answers `422`; while the first request
         *     runs, `409`. Keys expire after 24 hours.
         */
        IdempotencyKey: string;
        /** @description The organization to act in, for credentials that belong to several. */
        Organization: components["schemas"]["Uuid"];
        /** @description Restricts the list to one project (default every project the caller can access). */
        ProjectFilter: components["schemas"]["Uuid"];
        /** @description The `next_cursor` of the previous page. */
        Cursor: string;
        Limit: number;
        ScenarioId: components["schemas"]["Uuid"];
        RunId: components["schemas"]["Uuid"];
    };
    requestBodies: never;
    headers: {
        /** @description `true` when the response is the stored answer to an earlier request with the same `Idempotency-Key`. */
        IdempotentReplayed: "true";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTwins: {
        parameters: {
            query?: {
                /** @description Restricts the list to one project (default every project the caller can access). */
                project_id?: components["parameters"]["ProjectFilter"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The twins, ordered by project and name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwinList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    registerTwin: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description One key per user action (ADR-0019). A repeat of the same request
                 *     returns the stored response with `Idempotent-Replayed: true`; the same
                 *     key with a different request answers `422`; while the first request
                 *     runs, `409`. Keys expire after 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        responses: {
            /** @description The document equals the latest version; nothing was stored. */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterTwinResponse"];
                };
            };
            /** @description A new twin version was stored. */
            201: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterTwinResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getTwin: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                /** @description The id of a twin version. */
                twin_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The twin version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwinDetailResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    validateScenario: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description One key per user action (ADR-0019). A repeat of the same request
                 *     returns the stored response with `Idempotent-Replayed: true`; the same
                 *     key with a different request answers `422`; while the first request
                 *     runs, `409`. Keys expire after 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        responses: {
            /** @description The result of the checks. */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioValidation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    listScenarios: {
        parameters: {
            query?: {
                /** @description Restricts the list to one project (default every project the caller can access). */
                project_id?: components["parameters"]["ProjectFilter"];
                /** @description Scenarios for this agent, including those that name no agent. */
                agent?: string;
                severity?: components["schemas"]["Severity"];
                tag?: string;
                /** @description Substring of the name or the description (case-insensitive). */
                q?: string;
                /** @description Exact name ("is this name taken?" before saving). */
                name?: string;
                /** @description `1` or `true` includes archived scenarios. */
                include_archived?: "1" | "true" | "0" | "false";
                /** @description The `next_cursor` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of scenarios. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    saveScenario: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description One key per user action (ADR-0019). A repeat of the same request
                 *     returns the stored response with `Idempotent-Replayed: true`; the same
                 *     key with a different request answers `422`; while the first request
                 *     runs, `409`. Keys expire after 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        responses: {
            /** @description The document equals the latest version; nothing was stored. */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveScenarioResponse"];
                };
            };
            /** @description A new version was stored. */
            201: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveScenarioResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getScenario: {
        parameters: {
            query?: {
                /** @description The version to return (default the latest). */
                version?: number;
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                scenario_id: components["parameters"]["ScenarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The scenario version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    archiveScenario: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description One key per user action (ADR-0019). A repeat of the same request
                 *     returns the stored response with `Idempotent-Replayed: true`; the same
                 *     key with a different request answers `422`; while the first request
                 *     runs, `409`. Keys expire after 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                scenario_id: components["parameters"]["ScenarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived scenario. */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getSimulationCapabilities: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The capabilities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    listSimulations: {
        parameters: {
            query?: {
                /** @description Restricts the list to one project (default every project the caller can access). */
                project_id?: components["parameters"]["ProjectFilter"];
                agent?: string;
                status?: components["schemas"]["RunStatus"];
                /** @description Runs requested by one release evaluation. */
                eval_run_id?: components["schemas"]["Uuid"];
                /** @description The `next_cursor` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    startSimulation: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description One key per user action (ADR-0019). A repeat of the same request
                 *     returns the stored response with `Idempotent-Replayed: true`; the same
                 *     key with a different request answers `422`; while the first request
                 *     runs, `409`. Keys expire after 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSimulationRequest"];
            };
        };
        responses: {
            /** @description The run is queued. */
            202: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartSimulationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getSimulation: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getSimulationCase: {
        parameters: {
            query?: never;
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                run_id: components["parameters"]["RunId"];
                case_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The case. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    cancelSimulation: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description One key per user action (ADR-0019). A repeat of the same request
                 *     returns the stored response with `Idempotent-Replayed: true`; the same
                 *     key with a different request answers `422`; while the first request
                 *     runs, `409`. Keys expire after 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run is final. */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Cancellation requested; the run is still stopping. */
            202: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["IdempotencyInProgress"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    callTwinTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, unknown>;
            };
        };
        responses: {
            /** @description The twin's reply, or one of the endpoint's own refusals. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    searchTwinKnowledgeBase: {
        parameters: {
            query?: {
                /** @description The query (at most the first 1000 characters are used). */
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The best matching documents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseResults"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["TwinCredential"];
            409: components["responses"]["CaseNotRunning"];
            500: components["responses"]["Internal"];
        };
    };
    runAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description The conversation finished. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            /** @description The agent could not run the conversation. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentError"];
                };
            };
        };
    };
}
