/**
 * The trace API as its contract documents it. The types come from
 * packages/contracts/openapi/trace-service.openapi.yaml (`traces.gen.ts`,
 * regenerated by `pnpm gen:api`); the contract is checked against the service
 * on every test run (ADR-0021), so what compiles here is what the service does.
 *
 * - The hand-written types in `lib/types.ts` must accept every response the
 *   contract allows (`ClientTypesAcceptTheContract`).
 * - Every filter the trace explorer keeps in the URL is a documented query
 *   parameter of `listTraces`, with a value the service accepts
 *   (`ExplorerFiltersAreDocumented`).
 */
import type { TraceFilters } from "../trace-filters";
import type { ApiErrorBody, FacetsResponse, TraceDetail, TracePage, TraceStats } from "../types";
import * as contract from "./contract";
import type { Accepts, Sends, WireQuery } from "./contract";
import type { components, operations } from "./traces.gen";

export type TraceSchemas = components["schemas"];
export type TraceOperation = keyof operations;

/** The query parameters an operation documents. */
export type QueryOf<Op extends TraceOperation> = contract.QueryOf<operations, Op>;

/** The JSON body of one documented response of an operation. */
export type ResponseOf<
  Op extends TraceOperation,
  Status extends keyof contract.ResponsesOf<operations, Op>,
> = contract.ResponseOf<operations, Op, Status>;

/** What the overview reads from `GET /trace-stats`. */
export interface TraceStatsWindow {
  from: string;
  to: string;
  stats: TraceStats;
}

// ------------------------------------------------------------------ checks

/** Each hand-written response type accepts the documented response of the operation that returns it. */
export type ClientTypesAcceptTheContract = [
  Accepts<TracePage, ResponseOf<"listTraces", 200>>,
  Accepts<FacetsResponse, ResponseOf<"getTraceFacets", 200>>,
  Accepts<TraceDetail, ResponseOf<"getTrace", 200>>,
  Accepts<TraceStatsWindow, ResponseOf<"getTraceStats", 200>>,
  Accepts<ApiErrorBody, TraceSchemas["Error"]>,
];

/** The explorer's URL filters are `listTraces` parameters in their URL form. */
export type ExplorerFiltersAreDocumented = Sends<WireQuery<QueryOf<"listTraces">>, TraceFilters>;

/** The explorer keeps every value the service accepts for an enum filter (none is dropped). */
export type ExplorerFiltersCoverTheEnums = [
  Accepts<never, Exclude<TraceSchemas["TraceStatus"], NonNullable<TraceFilters["status"]>>>,
  Accepts<never, Exclude<TraceSchemas["OutcomeStatus"], NonNullable<TraceFilters["outcome"]>>>,
  Accepts<never, Exclude<TraceSchemas["TraceSource"], NonNullable<TraceFilters["source"]>>>,
];
