/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export spans (OTLP/HTTP)
         * @description An OTLP `ExportTraceServiceRequest`, as JSON or binary protobuf,
         *     optionally gzip-compressed. The API key decides the organization and
         *     project; it needs the `traces:write` scope.
         *
         *     Spans are validated one by one: a span with an invalid id, time range
         *     or name is rejected and counted in `partialSuccess` while the others
         *     are stored (`200`). Re-delivered spans are ignored, so retries are safe.
         *     The response and every error are in the encoding of the request —
         *     JSON for JSON, protobuf for protobuf.
         *
         *     Limits: 16 MiB on the wire, 32 MiB decompressed, 20 000 spans per
         *     request (`413`); 256 attributes per span and 128 events (the rest are
         *     dropped and the span is marked truncated).
         */
        post: operations["exportTraces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List traces
         * @description Traces of the projects the caller can read, newest first. Every filter
         *     narrows the list.
         */
        get: operations["listTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The filter options of the trace explorer
         * @description The distinct values of each filter dimension among the most recent
         *     10 000 traces since `from` (default: the last 30 days), at most 50 per
         *     dimension, most frequent first. `sampled` says whether the sample limit
         *     was reached, so the counts cover only the most recent traces.
         */
        get: operations["getTraceFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{trace_id}": {
        parameters: {
            query?: {
                /**
                 * @description The project of the trace. Needed only when the same trace id exists in
                 *     several projects of the organization (otherwise `409
                 *     AMBIGUOUS_TRACE`).
                 */
                project_id?: components["parameters"]["TraceProject"];
            };
            header?: never;
            path: {
                /** @description 32 hex characters (the OpenTelemetry trace id); matched case-insensitively. */
                trace_id: components["parameters"]["TraceId"];
            };
            cookie?: never;
        };
        /**
         * Get a trace with its spans, outcome and flags
         * @description Spans are in start order. Captured content appears on a span only when
         *     the project's capture policy kept it and its content retention has not
         *     passed.
         */
        get: operations["getTrace"];
        put?: never;
        post?: never;
        /**
         * Delete a trace (privacy request)
         * @description Deletes the trace with its spans, outcome and flags, and records the
         *     deletion in the audit log. Requires `settings.write`.
         */
        delete: operations["deleteTrace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{trace_id}/outcome": {
        parameters: {
            query?: {
                /**
                 * @description The project of the trace. Needed only when the same trace id exists in
                 *     several projects of the organization (otherwise `409
                 *     AMBIGUOUS_TRACE`).
                 */
                project_id?: components["parameters"]["TraceProject"];
            };
            header?: never;
            path: {
                /** @description 32 hex characters (the OpenTelemetry trace id); matched case-insensitively. */
                trace_id: components["parameters"]["TraceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record the outcome of a trace
         * @description Records — or replaces — the verified outcome of the trace. People
         *     need `review.write`; API keys (SDK outcome callbacks) need
         *     `traces:write`. An outcome is `verified` only with a verification
         *     source: an agent's final answer alone is not verification. When the
         *     agent claimed a status the verification contradicts, the outcome and
         *     the trace carry `contradiction`.
         *
         *     `verification_source` defaults to `human_review` for people and
         *     `unavailable` for API keys and services.
         */
        post: operations["recordOutcome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{trace_id}/flag": {
        parameters: {
            query?: {
                /**
                 * @description The project of the trace. Needed only when the same trace id exists in
                 *     several projects of the organization (otherwise `409
                 *     AMBIGUOUS_TRACE`).
                 */
                project_id?: components["parameters"]["TraceProject"];
            };
            header?: never;
            path: {
                /** @description 32 hex characters (the OpenTelemetry trace id); matched case-insensitively. */
                trace_id: components["parameters"]["TraceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flag a trace
         * @description Marks the trace for review — an incident, negative feedback or a
         *     manual flag — with a reason; the regression miner turns flagged
         *     traces into candidate regression cases. Requires `review.write`.
         */
        post: operations["flagTrace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trace-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trace statistics for dashboards
         * @description Aggregates over the traces started in `[from, to)` (default: the last
         *     7 days). A trace counts as an error when its status is `ERROR` or its
         *     outcome is `FAILURE`. The `by_*` groups hold the 20 largest groups
         *     (`by_outcome` all of them, `NONE` for traces without an outcome).
         */
        get: operations["getTraceStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /** Format: date-time */
        Timestamp: string;
        /** @description The OpenTelemetry trace id, 32 lower-case hex characters. */
        TraceId: string;
        /** @description The OpenTelemetry span id, 16 lower-case hex characters. */
        SpanId: string;
        /**
         * @description Who acted, `user:<id>`, `apikey:<id>` or `service:<name>`.
         * @example user:0190f3b4-0000-7000-8000-000000000001
         */
        Actor: string;
        /**
         * @description The status of the root span (`UNSET` until it arrives).
         * @enum {string}
         */
        TraceStatus: "OK" | "ERROR" | "UNSET";
        /** @enum {string} */
        OutcomeStatus: "SUCCESS" | "PARTIAL" | "FAILURE" | "UNKNOWN";
        /**
         * @description What verified the outcome. `unavailable` means nothing did: the
         *     outcome is then never `verified`.
         * @enum {string}
         */
        VerificationSource: "state_assertion" | "tool_twin_state" | "tool_result" | "external_callback" | "human_review" | "semantic_judge" | "unavailable";
        /**
         * @description What produced the trace (the `agenttwin.source` attribute; `production` when absent).
         * @enum {string}
         */
        TraceSource: "production" | "simulation" | "replay" | "eval" | "test";
        /**
         * @description The capture policy the trace was stored under (ADR-0012).
         * @enum {string}
         */
        ContentMode: "off" | "redacted" | "full";
        Error: {
            error: {
                /** @description Stable, machine-readable (e.g. `AMBIGUOUS_TRACE`). */
                code: string;
                /** @description For people; may change. */
                message: string;
                /** @description Equals the `X-Request-Id` response header. */
                request_id: string;
                /** @description Code-specific context (field names, problems). */
                details?: Record<string, unknown>;
            };
        };
        /**
         * @description The OTLP/JSON encoding of `ExportTraceServiceRequest`: lowerCamelCase
         *     keys, hex trace and span ids, 64-bit integers as decimal strings and
         *     enums as integers (or their names). As OTLP/JSON requires, fields the
         *     service does not read are ignored; the objects are open. Only what
         *     the service reads is described.
         */
        ExportTraceServiceRequest: {
            resourceSpans?: components["schemas"]["ResourceSpans"][];
        } & {
            [key: string]: unknown;
        };
        ResourceSpans: {
            resource?: {
                /** @description Resource attributes (`service.name`, `agenttwin.agent.name`, `deployment.environment.name`, …). */
                attributes?: components["schemas"]["KeyValue"][];
            } & {
                [key: string]: unknown;
            };
            scopeSpans?: components["schemas"]["ScopeSpans"][];
        } & {
            [key: string]: unknown;
        };
        ScopeSpans: {
            scope?: {
                name?: string;
                version?: string;
            } & {
                [key: string]: unknown;
            };
            spans?: components["schemas"]["OtlpSpan"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * @description One span. A span with a missing or invalid `traceId` or `spanId`, an
         *     empty `name`, or an end before its start is rejected on its own (see
         *     `partialSuccess`); the request is not.
         */
        OtlpSpan: {
            /** @description 32 hex characters, not all zero. */
            traceId?: string;
            /** @description 16 hex characters, not all zero. */
            spanId?: string;
            /** @description Empty (or absent) for a root span. */
            parentSpanId?: string;
            name?: string;
            /** @description The OTel span kind, `0`–`5` or its name (`SPAN_KIND_SERVER`, …). */
            kind?: unknown;
            /** @description A decimal string (or a number) of nanoseconds since the Unix epoch. */
            startTimeUnixNano?: unknown;
            /** @description A decimal string (or a number) of nanoseconds since the Unix epoch. */
            endTimeUnixNano?: unknown;
            /**
             * @description Span attributes — the OpenTelemetry GenAI semantic conventions and
             *     the `agenttwin.*` attributes (ADR-0003). Captured content
             *     (`gen_ai.input.messages`, …) is kept only as the project's capture
             *     policy allows.
             */
            attributes?: components["schemas"]["KeyValue"][];
            events?: ({
                /** @description Nanoseconds since the Unix epoch; an event without a valid time is dropped. */
                timeUnixNano?: unknown;
                name?: string;
                attributes?: components["schemas"]["KeyValue"][];
            } & {
                [key: string]: unknown;
            })[];
            status?: {
                /** @description `0` unset, `1` ok, `2` error (or the names `STATUS_CODE_*`). */
                code?: unknown;
                message?: string;
            } & {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        KeyValue: {
            key?: string;
            /**
             * @description An OTLP `AnyValue`: one of `stringValue`, `boolValue`, `intValue`
             *     (a decimal string or a number), `doubleValue`, `bytesValue`
             *     (base64), `arrayValue` (`{"values": [AnyValue]}`) or `kvlistValue`
             *     (`{"values": [KeyValue]}`). Values nested deeper than 8 levels are
             *     dropped.
             */
            value?: unknown;
        } & {
            [key: string]: unknown;
        };
        /** @description The OTLP/JSON `ExportTraceServiceResponse`; `{}` when every span was stored. */
        ExportTraceServiceResponse: {
            partialSuccess?: {
                /** @description The number of rejected spans (an int64, encoded as a decimal string). */
                rejectedSpans: string;
                /** @description The first reasons, `; `-separated. */
                errorMessage: string;
            };
        };
        /** @description The OTLP/JSON encoding of `google.rpc.Status`. */
        OtlpStatus: {
            /**
             * @description A `google.rpc.Code`: `3` INVALID_ARGUMENT (`400`, `415`), `16`
             *     UNAUTHENTICATED, `7` PERMISSION_DENIED, `8` RESOURCE_EXHAUSTED
             *     (`413`), `14` UNAVAILABLE (`503`). Like OTLP clients, decide on the
             *     HTTP status, not on this code.
             */
            code: number;
            message: string;
        };
        Trace: {
            project_id: components["schemas"]["Uuid"];
            trace_id: components["schemas"]["TraceId"];
            organization_id: components["schemas"]["Uuid"];
            /** @description The deployment environment; `unknown` when no span named one. */
            environment: string;
            agent_name: string | null;
            agent_version: string | null;
            session_id: string | null;
            release_id: string | null;
            commit_sha: string | null;
            source: components["schemas"]["TraceSource"];
            /** @description The simulation run the trace belongs to (`source` `simulation`). */
            simulation_run_id: string | null;
            scenario_id: string | null;
            /** @description `null` until the root span arrives. */
            root_span_id: components["schemas"]["SpanId"] | null;
            root_name: string | null;
            status: components["schemas"]["TraceStatus"];
            started_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            ended_at: string | null;
            /** @description Set when the trace is finalized. */
            duration_ms: number | null;
            span_count: number;
            model_call_count: number;
            tool_call_count: number;
            error_count: number;
            retry_count: number;
            input_tokens: number;
            output_tokens: number;
            /** @description `null` when no model call reported a cost and no price is configured for its model. */
            cost_usd: number | null;
            models: string[];
            tools: string[];
            policy_decisions: string[];
            /**
             * @description Deterministic failure signals for the explorer and the regression
             *     miner (e.g. `error`, `duplicate_side_effect`, `contradiction`,
             *     `timeout_after_mutation`, `outcome_failure`). New signals may be
             *     added; clients show unknown ones as they are.
             */
            signals: string[];
            prompt_hash: string | null;
            /** @description The GenAI semantic-convention version the spans were read as (`none` when unknown). */
            semconv_version: string;
            sdk_name: string | null;
            sdk_version: string | null;
            content_mode: components["schemas"]["ContentMode"];
            /** @description Captured content was dropped by the capture policy. */
            content_dropped: boolean;
            /** @description Attributes, events or identifiers were cut by the ingestion limits. */
            truncated: boolean;
            /** @description The outcome, reported on a span or recorded through the API. */
            outcome_status: components["schemas"]["OutcomeStatus"] | null;
            outcome_verified: boolean | null;
            human_reviewed: boolean;
            flagged: boolean;
            summary: components["schemas"]["TraceSummary"];
            /**
             * @description The trace settled and its summary was computed. A late span makes
             *     the service compute the summary again.
             */
            finalized: boolean;
            /** @description The content retention passed and captured content was removed. */
            content_purged: boolean;
            expires_at: components["schemas"]["Timestamp"];
        };
        /**
         * @description The deterministic structured summary of the trace (spec §45); the same
         *     object `trace.ingested.v1` publishes. It is `{}` until the trace is
         *     finalized, and complete afterwards; an outcome recorded before that
         *     shows as `outcome` and `outcome_verified` only.
         */
        TraceSummary: {
            agent?: string;
            agent_version?: string;
            outcome?: components["schemas"]["OutcomeStatus"] | null;
            outcome_verified?: boolean;
            /** @description The tools called, in first-call order. */
            tools?: string[];
            errors?: string[];
            /** @description Rule violations (e.g. `retry_without_idempotency_key`). */
            violations?: string[];
            policy_decisions?: string[];
            step_count?: number;
            retry_count?: number;
            cost_usd?: number;
            cost_known?: boolean;
            duration_ms?: number;
            model?: string | null;
            prompt_hash?: string | null;
            /** @description A state change the agent adapter or tool twin reported (key → `[before, after]`). */
            final_state_diff?: Record<string, unknown>;
            failing_tool?: string;
            last_successful_step?: string;
            error_type?: string;
            /** @description The tool calls as a short sequence (e.g. `lookup_order→refund_payment×2`). */
            tool_sequence_sketch?: string;
        };
        TracePage: {
            items: components["schemas"]["Trace"][];
            /** @description The cursor of the next page; `null` on the last page. */
            next_cursor: string | null;
        };
        TraceDetail: {
            trace: components["schemas"]["Trace"];
            /** @description The spans in start order (at most 20 000). */
            spans: components["schemas"]["Span"][];
            outcome: components["schemas"]["Outcome"] | null;
            /** @description Oldest first. */
            flags: components["schemas"]["Flag"][];
        };
        Span: {
            span_id: components["schemas"]["SpanId"];
            parent_span_id: components["schemas"]["SpanId"] | null;
            name: string;
            /**
             * @description The normalized kind, read from the semantic conventions.
             * @enum {string}
             */
            kind: "agent" | "model" | "tool" | "retrieval" | "policy" | "outcome" | "http" | "mcp" | "other";
            status: components["schemas"]["TraceStatus"];
            status_message: string | null;
            started_at: components["schemas"]["Timestamp"];
            ended_at: components["schemas"]["Timestamp"];
            duration_ms: number;
            tool_name: string | null;
            tool_risk: string | null;
            /** @description The response model, or the requested one. */
            model: string | null;
            policy_decision: string | null;
            attributes: components["schemas"]["SpanAttributes"];
            events: components["schemas"]["SpanEvent"][];
            content?: components["schemas"]["SpanContent"];
            semconv_version: string;
        };
        /**
         * @description The normalized facts of the span (ADR-0003): the service's own names,
         *     independent of the semantic-convention version the span was written
         *     with. Only the facts the span carried are present.
         */
        SpanAttributes: {
            operation?: string;
            agent_name?: string;
            agent_version?: string;
            agent_id?: string;
            session_id?: string;
            environment?: string;
            source?: string;
            release_id?: string;
            commit_sha?: string;
            provider?: string;
            request_model?: string;
            response_model?: string;
            input_tokens?: number;
            output_tokens?: number;
            temperature?: number;
            max_tokens?: number;
            finish_reasons?: string[];
            cost_usd?: number;
            prompt_hash?: string;
            prompt_version?: string;
            tool_name?: string;
            tool_version?: string;
            tool_call_id?: string;
            tool_risk?: string;
            tool_args_hash?: string;
            tool_result_status?: string;
            idempotency_key_hash?: string;
            attempt?: number;
            retrieval_source?: string;
            document_count?: number;
            error_type?: string;
            exception_type?: string;
            exception_message?: string;
            policy_decision?: string;
            policy_name?: string;
            policy_version?: string;
            policy_rule?: string;
            outcome_status?: string;
            outcome_claimed?: string;
            business_outcome?: string;
            outcome_verified?: boolean;
            verification_source?: string;
            http_method?: string;
            http_host?: string;
            http_status?: number;
            mcp_method?: string;
            mcp_server?: string;
            simulation_run_id?: string;
            scenario_id?: string;
            /** @description A state change (key → `[before, after]`). */
            final_state_diff?: Record<string, unknown>;
            /** @description The remaining non-content attributes, bounded and sanitized. */
            extra?: Record<string, unknown>;
        };
        SpanEvent: {
            name: string;
            time: components["schemas"]["Timestamp"];
            attributes?: Record<string, unknown>;
        };
        /**
         * @description Captured content, present only when the project's capture policy
         *     (ADR-0012) kept it and its content retention has not passed. In
         *     `redacted` mode sensitive values appear masked (`[REDACTED:email]`).
         */
        SpanContent: {
            input?: string;
            /**
             * @description The request context the run acted in (tenant, customer, ...), as
             *     the SDK recorded it (`agenttwin.input.context`): JSON text. A
             *     regression's scenario draft replays it (ADR-0032).
             */
            input_context?: string;
            output?: string;
            system_instructions?: string;
            tool_args?: string;
            tool_result?: string;
        };
        TraceFacets: {
            from: components["schemas"]["Timestamp"];
            facets: {
                agent: components["schemas"]["FacetValues"];
                agent_version: components["schemas"]["FacetValues"];
                environment: components["schemas"]["FacetValues"];
                release: components["schemas"]["FacetValues"];
                source: components["schemas"]["FacetValues"];
                status: components["schemas"]["FacetValues"];
                outcome: components["schemas"]["FacetValues"];
                model: components["schemas"]["FacetValues"];
                tool: components["schemas"]["FacetValues"];
                signal: components["schemas"]["FacetValues"];
                policy_decision: components["schemas"]["FacetValues"];
            };
            sampled: boolean;
        };
        /** @description The values of one dimension, most frequent first (at most 50). */
        FacetValues: {
            value: string;
            count: number;
        }[];
        TraceStatsResponse: {
            from: components["schemas"]["Timestamp"];
            to: components["schemas"]["Timestamp"];
            stats: components["schemas"]["TraceStats"];
        };
        TraceStats: {
            total: number;
            errors: number;
            error_rate: number;
            /** @description `null` when no trace in the range has a duration. */
            p50_ms: number | null;
            p95_ms: number | null;
            cost_usd: number;
            by_outcome: components["schemas"]["Counts"];
            by_signal: components["schemas"]["Counts"];
            by_tool: components["schemas"]["Counts"];
            by_agent_version: components["schemas"]["Counts"];
            /** @description Traces with an outcome that is not verified. */
            unverified_outcomes: number;
            contradictions: number;
        };
        Counts: {
            [key: string]: number;
        };
        RecordOutcomeRequest: {
            status: components["schemas"]["OutcomeStatus"];
            /** @description What the outcome means for the business (e.g. `refund_issued`). */
            business_outcome?: string;
            /** @default false */
            verified?: boolean;
            verification_source?: components["schemas"]["VerificationSource"];
            /** @description What the agent claimed, if it claimed anything. */
            claimed_status?: components["schemas"]["OutcomeStatus"];
            /** @description The state the verification expected. */
            expected_state?: Record<string, unknown> | null;
            /** @description The state it found. */
            actual_state?: Record<string, unknown> | null;
            notes?: string;
        };
        Outcome: {
            status: components["schemas"]["OutcomeStatus"];
            business_outcome: string | null;
            verified: boolean;
            verification_source: components["schemas"]["VerificationSource"];
            claimed_status: components["schemas"]["OutcomeStatus"] | null;
            /** @description The agent claimed a status the verification disproved. */
            contradiction: boolean;
            /** @description Present when it was recorded. */
            expected_state?: Record<string, unknown>;
            /** @description Present when it was recorded. */
            actual_state?: Record<string, unknown>;
            notes: string | null;
            /**
             * @description `span` when an outcome span reported it, `api` when it was recorded through this API.
             * @enum {string}
             */
            source: "span" | "api";
            recorded_by: components["schemas"]["Actor"];
            recorded_at: components["schemas"]["Timestamp"];
        };
        FlagRequest: {
            kind?: components["schemas"]["FlagKind"];
            /** @description Why; surrounding whitespace is removed and at least one other character must remain. */
            reason: string;
        };
        /**
         * @default manual
         * @enum {string}
         */
        FlagKind: "incident" | "negative_feedback" | "manual";
        Flag: {
            id: components["schemas"]["Uuid"];
            kind: components["schemas"]["FlagKind"];
            reason: string;
            flagged_by: components["schemas"]["Actor"];
            created_at: components["schemas"]["Timestamp"];
        };
    };
    responses: {
        /** @description The body is not a valid OTLP export request (malformed JSON or protobuf, or invalid gzip). */
        OtlpBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OtlpStatus"];
                "application/x-protobuf": unknown;
            };
        };
        /** @description The API key is missing, unknown, revoked or expired. */
        OtlpUnauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OtlpStatus"];
                "application/x-protobuf": unknown;
            };
        };
        /** @description The API key lacks the `traces:write` scope. */
        OtlpForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OtlpStatus"];
                "application/x-protobuf": unknown;
            };
        };
        /** @description The request is larger than the limits allow; split it into smaller exports. */
        OtlpTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OtlpStatus"];
                "application/x-protobuf": unknown;
            };
        };
        /** @description The `Content-Type` is not `application/json` or `application/x-protobuf`, or the `Content-Encoding` is not `gzip`. */
        OtlpUnsupported: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OtlpStatus"];
                "application/x-protobuf": unknown;
            };
        };
        /**
         * @description Ingestion is at capacity, trace storage is unavailable, or the API key
         *     cannot be verified right now. Retry after `Retry-After` seconds (OTLP
         *     exporters do this on their own).
         */
        OtlpUnavailable: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OtlpStatus"];
                "application/x-protobuf": unknown;
            };
        };
        /**
         * @description The request is invalid. `INVALID_PARAMETER` (a malformed id or limit;
         *     `details.field`), `INVALID_FILTER` (`details.field`), `INVALID_CURSOR`,
         *     `INVALID_JSON` (a malformed body or an unknown field;
         *     `details.reason`), `EMPTY_BODY`, `INVALID_IDEMPOTENCY_KEY` or an
         *     operation-specific code (`INVALID_OUTCOME`, `INVALID_FLAG`; both with
         *     `details.field`).
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid credential (`UNAUTHENTICATED`). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The credential lacks the permission (`FORBIDDEN`; `details.required_permission`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The trace does not exist, or it or the project is outside the caller's access (`NOT_FOUND`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The trace id exists in several projects; pass `project_id` (`AMBIGUOUS_TRACE`). */
        AmbiguousTrace: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The trace id exists in several projects; pass `project_id`
         *     (`AMBIGUOUS_TRACE`) — or the first request with this `Idempotency-Key`
         *     is still running (`IDEMPOTENCY_IN_PROGRESS`).
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request body is too large (`PAYLOAD_TOO_LARGE`). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The body is not `application/json` (`UNSUPPORTED_MEDIA_TYPE`). */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The `Idempotency-Key` was used for a different request (`IDEMPOTENCY_KEY_REUSED`). */
        IdempotencyKeyReused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests (`RATE_LIMITED`). */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description An unexpected error (`INTERNAL`); quote the `request_id`. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The trace service is not reachable from the control plane (`UPSTREAM_UNAVAILABLE`). */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The trace service is not configured on this control plane (`SERVICE_NOT_CONFIGURED`). */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description One key per user action (ADR-0019), applied by the control plane. A
         *     repeat of the same request returns the stored response with
         *     `Idempotent-Replayed: true`; the same key with a different request
         *     answers `422`; while the first request runs, `409`. Keys expire after
         *     24 hours.
         */
        IdempotencyKey: string;
        /** @description The organization to act in, for credentials that belong to several. */
        Organization: components["schemas"]["Uuid"];
        /**
         * @description Restricts the result to one project (default: every project the caller
         *     can read). A malformed id answers `400 INVALID_FILTER`, a project
         *     outside the caller's access `404`.
         */
        ProjectFilter: components["schemas"]["Uuid"];
        /**
         * @description The project of the trace. Needed only when the same trace id exists in
         *     several projects of the organization (otherwise `409
         *     AMBIGUOUS_TRACE`).
         */
        TraceProject: components["schemas"]["Uuid"];
        /** @description 32 hex characters (the OpenTelemetry trace id); matched case-insensitively. */
        TraceId: string;
        /** @description Only traces started at or after this time. */
        From: components["schemas"]["Timestamp"];
        /** @description Only traces started before this time. */
        To: components["schemas"]["Timestamp"];
    };
    requestBodies: never;
    headers: {
        /** @description `true` when the response is the stored answer to an earlier request with the same `Idempotency-Key`. */
        IdempotentReplayed: "true";
        /** @description Seconds to wait before retrying. */
        RetryAfter: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exportTraces: {
        parameters: {
            query?: never;
            header?: {
                "Content-Encoding"?: "gzip" | "identity";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportTraceServiceRequest"];
                "application/x-protobuf": unknown;
                "application/protobuf": unknown;
            };
        };
        responses: {
            /**
             * @description The request was stored; rejected spans, if any, are counted in
             *     `partialSuccess`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTraceServiceResponse"];
                    "application/x-protobuf": unknown;
                };
            };
            400: components["responses"]["OtlpBadRequest"];
            401: components["responses"]["OtlpUnauthenticated"];
            403: components["responses"]["OtlpForbidden"];
            413: components["responses"]["OtlpTooLarge"];
            415: components["responses"]["OtlpUnsupported"];
            503: components["responses"]["OtlpUnavailable"];
        };
    };
    listTraces: {
        parameters: {
            query?: {
                /**
                 * @description Restricts the result to one project (default: every project the caller
                 *     can read). A malformed id answers `400 INVALID_FILTER`, a project
                 *     outside the caller's access `404`.
                 */
                project_id?: components["parameters"]["ProjectFilter"];
                agent?: string;
                agent_version?: string;
                environment?: string;
                /** @description The release id. */
                release?: string;
                /** @description Traces that called this model. */
                model?: string;
                /** @description Traces that called this tool. */
                tool?: string;
                status?: components["schemas"]["TraceStatus"];
                outcome?: components["schemas"]["OutcomeStatus"];
                /** @description Traces carrying this signal (e.g. `duplicate_side_effect`). */
                signal?: string;
                /** @description Traces with a policy decision of this kind (e.g. `deny`). */
                policy_decision?: string;
                source?: components["schemas"]["TraceSource"];
                session_id?: string;
                simulation_run_id?: string;
                /** @description Only traces started at or after this time. */
                from?: components["parameters"]["From"];
                /** @description Only traces started before this time. */
                to?: components["parameters"]["To"];
                min_duration_ms?: number;
                max_duration_ms?: number;
                min_cost_usd?: number;
                max_cost_usd?: number;
                human_reviewed?: boolean;
                flagged?: boolean;
                limit?: number;
                /** @description The `next_cursor` of the previous page. */
                cursor?: string;
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of traces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getTraceFacets: {
        parameters: {
            query?: {
                /**
                 * @description Restricts the result to one project (default: every project the caller
                 *     can read). A malformed id answers `400 INVALID_FILTER`, a project
                 *     outside the caller's access `404`.
                 */
                project_id?: components["parameters"]["ProjectFilter"];
                /** @description Only traces started at or after this time. */
                from?: components["parameters"]["From"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The filter options. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceFacets"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getTrace: {
        parameters: {
            query?: {
                /**
                 * @description The project of the trace. Needed only when the same trace id exists in
                 *     several projects of the organization (otherwise `409
                 *     AMBIGUOUS_TRACE`).
                 */
                project_id?: components["parameters"]["TraceProject"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                /** @description 32 hex characters (the OpenTelemetry trace id); matched case-insensitively. */
                trace_id: components["parameters"]["TraceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The trace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["AmbiguousTrace"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteTrace: {
        parameters: {
            query?: {
                /**
                 * @description The project of the trace. Needed only when the same trace id exists in
                 *     several projects of the organization (otherwise `409
                 *     AMBIGUOUS_TRACE`).
                 */
                project_id?: components["parameters"]["TraceProject"];
            };
            header?: {
                /**
                 * @description One key per user action (ADR-0019), applied by the control plane. A
                 *     repeat of the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                /** @description 32 hex characters (the OpenTelemetry trace id); matched case-insensitively. */
                trace_id: components["parameters"]["TraceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The trace was deleted. */
            204: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    recordOutcome: {
        parameters: {
            query?: {
                /**
                 * @description The project of the trace. Needed only when the same trace id exists in
                 *     several projects of the organization (otherwise `409
                 *     AMBIGUOUS_TRACE`).
                 */
                project_id?: components["parameters"]["TraceProject"];
            };
            header?: {
                /**
                 * @description One key per user action (ADR-0019), applied by the control plane. A
                 *     repeat of the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                /** @description 32 hex characters (the OpenTelemetry trace id); matched case-insensitively. */
                trace_id: components["parameters"]["TraceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordOutcomeRequest"];
            };
        };
        responses: {
            /** @description The stored outcome. */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Outcome"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    flagTrace: {
        parameters: {
            query?: {
                /**
                 * @description The project of the trace. Needed only when the same trace id exists in
                 *     several projects of the organization (otherwise `409
                 *     AMBIGUOUS_TRACE`).
                 */
                project_id?: components["parameters"]["TraceProject"];
            };
            header?: {
                /**
                 * @description One key per user action (ADR-0019), applied by the control plane. A
                 *     repeat of the same request returns the stored response with
                 *     `Idempotent-Replayed: true`; the same key with a different request
                 *     answers `422`; while the first request runs, `409`. Keys expire after
                 *     24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path: {
                /** @description 32 hex characters (the OpenTelemetry trace id); matched case-insensitively. */
                trace_id: components["parameters"]["TraceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlagRequest"];
            };
        };
        responses: {
            /** @description The flag. */
            201: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flag"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IdempotencyKeyReused"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getTraceStats: {
        parameters: {
            query?: {
                /**
                 * @description Restricts the result to one project (default: every project the caller
                 *     can read). A malformed id answers `400 INVALID_FILTER`, a project
                 *     outside the caller's access `404`.
                 */
                project_id?: components["parameters"]["ProjectFilter"];
                /** @description Only traces started at or after this time. */
                from?: components["parameters"]["From"];
                /** @description Only traces started before this time. */
                to?: components["parameters"]["To"];
            };
            header?: {
                /** @description The organization to act in, for credentials that belong to several. */
                "X-AgentTwin-Org"?: components["parameters"]["Organization"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceStatsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
}
