/**
 * The dark half of the colour palette, generated from Tailwind's own colours
 * (ADR-0035).
 *
 *   node scripts/theme-palette.ts           write src/app/palette.css
 *   node scripts/theme-palette.ts --check   fail when the committed file is stale
 *
 * Every Tailwind colour variable becomes `light-dark(light, dark)`: the light
 * value is Tailwind's, the dark one the same family's shade mirrored (50 → 950,
 * 100 → 800, … 900 → 50, 950 → white); `white`, the surface of cards and
 * panels, becomes slate-900, and `black` white. Components keep writing
 * `bg-white text-slate-900`; the page's `color-scheme` picks the half. A unit
 * test runs the same check, and holds every colour pair the components use
 * to WCAG AA in both themes.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const WEB = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const PALETTE_FILE = path.join(WEB, "src/app/palette.css");

export const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;
export type Shade = (typeof SHADES)[number];

/** The shade a colour takes in the dark theme ("white" for the lightest). */
export const DARK_SHADE: Readonly<Record<Shade, Shade | "white">> = {
  50: 950,
  100: 800,
  200: 700,
  300: 600,
  400: 500,
  500: 400,
  600: 300,
  700: 200,
  800: 100,
  900: 50,
  950: "white",
};

/** The dark surface `white` stands for. */
export const DARK_WHITE = { family: "slate", shade: 900 } as const;

export interface TailwindColors {
  readonly white: string;
  readonly black: string;
  /** family → shade → CSS colour. */
  readonly families: ReadonlyMap<string, ReadonlyMap<Shade, string>>;
}

/** Reads the colour variables of Tailwind's `theme.css`. */
export function parseTailwindColors(css: string): TailwindColors {
  const families = new Map<string, Map<Shade, string>>();
  let white: string | undefined;
  let black: string | undefined;
  for (const m of css.matchAll(/--color-([a-z]+)(?:-(\d+))?:\s*([^;]+);/g)) {
    const [, name, shade, value] = m as unknown as [string, string, string | undefined, string];
    if (shade === undefined) {
      if (name === "white") white = value.trim();
      if (name === "black") black = value.trim();
      continue;
    }
    const s = Number(shade) as Shade;
    if (!SHADES.includes(s)) continue;
    let family = families.get(name);
    if (!family) families.set(name, (family = new Map()));
    family.set(s, value.trim());
  }
  if (white === undefined || black === undefined)
    throw new Error("theme.css has no --color-white/--color-black");
  for (const [name, family] of families) {
    if (family.size !== SHADES.length)
      throw new Error(`--color-${name} does not have all ${SHADES.length} shades`);
  }
  if (!families.has(DARK_WHITE.family)) throw new Error(`theme.css has no --color-${DARK_WHITE.family}`);
  return { white, black, families };
}

/** The dark value of each variable, by name (`white`, `slate-900`, …). */
export function darkValues(colors: TailwindColors): Map<string, string> {
  const out = new Map<string, string>();
  out.set("white", colors.families.get(DARK_WHITE.family)!.get(DARK_WHITE.shade)!);
  out.set("black", colors.white);
  for (const [name, family] of colors.families) {
    for (const shade of SHADES) {
      const to = DARK_SHADE[shade];
      out.set(`${name}-${shade}`, to === "white" ? colors.white : family.get(to)!);
    }
  }
  return out;
}

/** The light value of each variable, by name. */
export function lightValues(colors: TailwindColors): Map<string, string> {
  const out = new Map<string, string>([
    ["white", colors.white],
    ["black", colors.black],
  ]);
  for (const [name, family] of colors.families) {
    for (const shade of SHADES) out.set(`${name}-${shade}`, family.get(shade)!);
  }
  return out;
}

export function renderPalette(colors: TailwindColors): string {
  const light = lightValues(colors);
  const dark = darkValues(colors);
  const lines = [...light.keys()].map(
    (name) => `    --color-${name}: light-dark(${light.get(name)}, ${dark.get(name)});`,
  );
  return [
    "/* Generated by scripts/theme-palette.ts from Tailwind's colours; do not edit. */",
    "/* Each colour in both themes: light-dark() follows the page's color-scheme. */",
    "@supports (color: light-dark(#000, #fff)) {",
    "  :root {",
    ...lines,
    "  }",
    "}",
    "",
  ].join("\n");
}

export function tailwindThemeCss(): string {
  const require = createRequire(import.meta.url);
  return readFileSync(require.resolve("tailwindcss/theme.css"), "utf8");
}

function main(): void {
  const expected = renderPalette(parseTailwindColors(tailwindThemeCss()));
  if (process.argv.includes("--check")) {
    const current = readFileSync(PALETTE_FILE, "utf8");
    if (current !== expected) {
      console.error(`${path.relative(WEB, PALETTE_FILE)} is stale: run node scripts/theme-palette.ts`);
      process.exit(1);
    }
    return;
  }
  writeFileSync(PALETTE_FILE, expected);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
