/**
 * Regressions as the evaluation service answered them in its integration
 * tests (services/evaluation-service/tests/test_regressions_api_integration.py,
 * with AGENTTWIN_CAPTURE_DIR set): the demo's 1.3.0 duplicate refund, mined,
 * drafted, promoted and fixed by 1.3.1. Verbatim. Typed by the API contract
 * (`satisfies`), so a fixture the service could not send does not compile.
 */
import type {
  PromoteResponse,
  RegressionDetail,
  RegressionDraft,
  RegressionPage,
} from "@/lib/api/evaluation";

/** The inbox: the incident (a duplicate refund), a handled timeout someone triaged, a correct refusal someone dismissed. */
export const liveRegressionInbox = {
  items: [
    {
      agent: "support-refund-agent",
      assignee: null,
      component: "lookup_order",
      created_at: "2026-09-25T17:52:02.506754Z",
      dataset_id: null,
      dataset_version: null,
      environments: ["production"],
      evidence: ["AUTHORIZATION: access was denied to lookup_order"],
      fingerprint: "5aa553da296c4a9cd615ae9e59345723",
      first_seen: "2026-09-25T16:00:10.343846Z",
      fixed_eval_run_id: null,
      fixed_version: null,
      id: "01a0d9b2-17cd-71b0-9691-a7c25e7fc8ab",
      last_seen: "2026-09-25T16:00:10.343846Z",
      merged_into: null,
      occurrence_count: 1,
      organization_id: "0190f3b4-0000-7000-8000-00000000000a",
      project_id: "0190f3b4-0000-7000-8000-0000000000b1",
      promoted_at: null,
      promoted_by: null,
      representative_trace_id: "922fd31a879d97f422314843ca23e072",
      scenario_id: null,
      scenario_name: null,
      secondary: [],
      severity: "high",
      severity_reason: "AUTHORIZATION is high",
      status: "DISMISSED",
      suggested_severity: "high",
      suggested_taxonomy: "AUTHORIZATION",
      tags: [],
      taxonomy: "AUTHORIZATION",
      title: "Access to lookup_order was denied",
      triaged_by: null,
      updated_at: "2026-09-25T17:52:02.519022Z",
      versions: ["1.3.0"],
    },
    {
      agent: "support-refund-agent",
      assignee: null,
      component: "refund_payment",
      created_at: "2026-09-25T17:52:02.425076Z",
      dataset_id: null,
      dataset_version: null,
      environments: ["production"],
      evidence: [
        "DUPLICATE_SIDE_EFFECT: refund_payment took effect more than once",
        "HALLUCINATED_SUCCESS: the agent claimed success and the verified outcome disproved it",
        "RETRY_SAFETY: a write was retried without an idempotency key",
        "TIMEOUT: refund_payment timed out",
      ],
      fingerprint: "ba8e6fcdd752b75c2074e3812a7f2833",
      first_seen: "2026-09-25T15:59:53.152630Z",
      fixed_eval_run_id: null,
      fixed_version: null,
      id: "01a0d9b2-177f-7086-8b59-7f8801edc1a0",
      last_seen: "2026-09-25T15:59:53.152630Z",
      merged_into: null,
      occurrence_count: 1,
      organization_id: "0190f3b4-0000-7000-8000-00000000000a",
      project_id: "0190f3b4-0000-7000-8000-0000000000b1",
      promoted_at: null,
      promoted_by: null,
      representative_trace_id: "f310c0de303dcad73b1f5f0b10509536",
      scenario_id: null,
      scenario_name: null,
      secondary: ["HALLUCINATED_SUCCESS", "RETRY_SAFETY", "TIMEOUT"],
      severity: "critical",
      severity_reason: "DUPLICATE_SIDE_EFFECT is critical",
      status: "CANDIDATE",
      suggested_severity: "critical",
      suggested_taxonomy: "DUPLICATE_SIDE_EFFECT",
      tags: [],
      taxonomy: "DUPLICATE_SIDE_EFFECT",
      title: "refund_payment took effect twice",
      triaged_by: null,
      updated_at: "2026-09-25T17:52:02.425076Z",
      versions: ["1.3.0"],
    },
    {
      agent: "support-refund-agent",
      assignee: "user:reviewer",
      component: "refund_payment",
      created_at: "2026-09-25T17:52:02.482054Z",
      dataset_id: null,
      dataset_version: null,
      environments: ["production"],
      evidence: ["TIMEOUT: refund_payment timed out"],
      fingerprint: "091a69215b8ce9f0e2c05ae018034067",
      first_seen: "2026-09-25T15:28:34.978171Z",
      fixed_eval_run_id: null,
      fixed_version: null,
      id: "01a0d9b2-17b4-721b-8eb5-56661d92512b",
      last_seen: "2026-09-25T15:28:34.978171Z",
      merged_into: null,
      occurrence_count: 1,
      organization_id: "0190f3b4-0000-7000-8000-00000000000a",
      project_id: "0190f3b4-0000-7000-8000-0000000000b1",
      promoted_at: null,
      promoted_by: null,
      representative_trace_id: "98aaf18f676eebc9b0e5b754698b458a",
      scenario_id: null,
      scenario_name: null,
      secondary: [],
      severity: "low",
      severity_reason: "set by user:engineer",
      status: "CANDIDATE",
      suggested_severity: "medium",
      suggested_taxonomy: "TIMEOUT",
      tags: ["payments"],
      taxonomy: "TIMEOUT",
      title: "refund_payment timed out",
      triaged_by: "user:engineer",
      updated_at: "2026-09-25T17:52:02.495004Z",
      versions: ["1.2.4"],
    },
  ],
  next_cursor: null,
} satisfies RegressionPage;

/** The duplicate refund as the miner left it: one failure, its creation. */
export const liveCandidate = {
  events: [
    {
      action: "created",
      actor: "system:regression-miner",
      at: "2026-09-25T17:52:02.425076Z",
      detail: {
        fingerprint: "ba8e6fcdd752b75c2074e3812a7f2833",
        trace_id: "f310c0de303dcad73b1f5f0b10509536",
      },
      from_status: null,
      reason: "the first failure of its kind",
      seq: 1,
      to_status: "CANDIDATE",
    },
  ],
  occurrences: [
    {
      agent_version: "1.3.0",
      component: "refund_payment",
      created_at: "2026-09-25T17:52:02.425076Z",
      environment: "production",
      evidence: [
        "DUPLICATE_SIDE_EFFECT: refund_payment took effect more than once",
        "HALLUCINATED_SUCCESS: the agent claimed success and the verified outcome disproved it",
        "RETRY_SAFETY: a write was retried without an idempotency key",
        "TIMEOUT: refund_payment timed out",
      ],
      join_kind: "new",
      join_reason: "the first failure of its kind",
      reasons: [
        "the outcome was FAILURE",
        "it claimed a success the verified outcome disproved",
        "it took an irreversible action twice",
        "it retried a write without an idempotency key",
        "a tool timed out after it may have changed state",
        "a tool failed (refund_payment)",
      ],
      secondary: ["HALLUCINATED_SUCCESS", "RETRY_SAFETY", "TIMEOUT"],
      severity: "critical",
      severity_reason: "DUPLICATE_SIDE_EFFECT is critical",
      similarity: null,
      started_at: "2026-09-25T15:59:53.152630Z",
      taxonomy: "DUPLICATE_SIDE_EFFECT",
      title: "refund_payment took effect twice",
      trace_id: "f310c0de303dcad73b1f5f0b10509536",
    },
  ],
  regression: {
    agent: "support-refund-agent",
    assignee: null,
    component: "refund_payment",
    created_at: "2026-09-25T17:52:02.425076Z",
    dataset_id: null,
    dataset_version: null,
    environments: ["production"],
    evidence: [
      "DUPLICATE_SIDE_EFFECT: refund_payment took effect more than once",
      "HALLUCINATED_SUCCESS: the agent claimed success and the verified outcome disproved it",
      "RETRY_SAFETY: a write was retried without an idempotency key",
      "TIMEOUT: refund_payment timed out",
    ],
    fingerprint: "ba8e6fcdd752b75c2074e3812a7f2833",
    first_seen: "2026-09-25T15:59:53.152630Z",
    fixed_eval_run_id: null,
    fixed_version: null,
    id: "01a0d9b2-177f-7086-8b59-7f8801edc1a0",
    last_seen: "2026-09-25T15:59:53.152630Z",
    merged_into: null,
    occurrence_count: 1,
    organization_id: "0190f3b4-0000-7000-8000-00000000000a",
    project_id: "0190f3b4-0000-7000-8000-0000000000b1",
    promoted_at: null,
    promoted_by: null,
    representative_trace_id: "f310c0de303dcad73b1f5f0b10509536",
    scenario_id: null,
    scenario_name: null,
    secondary: ["HALLUCINATED_SUCCESS", "RETRY_SAFETY", "TIMEOUT"],
    severity: "critical",
    severity_reason: "DUPLICATE_SIDE_EFFECT is critical",
    status: "CANDIDATE",
    suggested_severity: "critical",
    suggested_taxonomy: "DUPLICATE_SIDE_EFFECT",
    tags: [],
    taxonomy: "DUPLICATE_SIDE_EFFECT",
    title: "refund_payment took effect twice",
    triaged_by: null,
    updated_at: "2026-09-25T17:52:02.425076Z",
    versions: ["1.3.0"],
  },
} satisfies RegressionDetail;

/** Its draft: complete, the order mapped onto a twin record. */
export const liveDraft = {
  draft: {
    complete: true,
    document: {
      apiVersion: "agenttwin.dev/v1",
      kind: "Scenario",
      metadata: {
        description:
          "Mined from production trace f310c0de303dcad73b1f5f0b10509536 (support-refund-agent 1.3.0, 2026-09-25): refund_payment took effect twice.",
        generated: {
          by: "agenttwin-regression-miner",
          evidence: [
            "DUPLICATE_SIDE_EFFECT: refund_payment took effect more than once",
            "HALLUCINATED_SUCCESS: the agent claimed success and the verified outcome disproved it",
            "RETRY_SAFETY: a write was retried without an idempotency key",
            "TIMEOUT: refund_payment timed out",
          ],
          reviewed: false,
        },
        name: "regression-refund-payment-took-effect-twice-edc1a0",
        severity: "critical",
        source: "production_regression",
        sourceTraceId: "f310c0de303dcad73b1f5f0b10509536",
        tags: ["duplicate-side-effect", "production-regression"],
      },
      spec: {
        agent: "support-refund-agent",
        covers: [
          "fault:timeout_after_mutation",
          "tool:lookup_order",
          "tool:refund_payment",
          "tool:send_email",
        ],
        expectations: [
          {
            critical: true,
            description: "In production refund_payment was called 2 times and took effect more than once.",
            id: "no-duplicate-refund-payment",
            tool: "refund_payment",
            type: "noDuplicateSideEffect",
          },
          {
            critical: true,
            description: "In production the agent claimed success and the verified outcome disproved it.",
            equals: 1,
            id: "success-backed-by-state",
            path: "orders.ORD-1001.refund_count",
            type: "outcomeVerified",
          },
          {
            critical: true,
            description: "The verified outcome expected refunded_amount = 40.0; production ended at 80.0.",
            equals: 40,
            id: "state-refunded-amount",
            path: "orders.ORD-1001.refunded_amount",
            type: "state",
          },
        ],
        faults: [
          {
            behavior: {
              message: "Reproduces the production trace f310c0de303dcad73b1f5f0b10509536.",
              type: "timeout_after_mutation",
            },
            target: "refund_payment",
            when: {
              callNumber: 1,
            },
          },
        ],
        input: {
          message: "Hi! One item in ORD-1001 arrived broken. Can I get a refund of $40?",
        },
        twin: "demo-co-support",
      },
    },
    mappings: [
      {
        added: false,
        agreeing: ["currency", "customer_id", "refund_count", "refunded_amount", "status"],
        collection: "orders",
        differing: [
          {
            field: "delivered_at",
            observed: "2026-09-21T15:28:04.434811+00:00",
            twin: "2026-09-19T10:00:00Z",
          },
          {
            field: "total",
            observed: 140,
            twin: 150,
          },
        ],
        reason:
          "ORD-3036 is not in the twin; the draft uses the twin's record ORD-1001: it agrees on 5 of 7 observed field(s).",
        source_id: "ORD-3036",
        target_id: "ORD-1001",
      },
    ],
    notes: [
      "The trace did not record the request's tenant; entities are mapped without it.",
      "ORD-3036 is not in the twin; the draft uses the twin's record ORD-1001: it agrees on 5 of 7 observed field(s).",
      "refund_payment timed out on call 1. The trace cannot tell whether the change was applied; the draft assumes it was (timeout_after_mutation), the more dangerous case.",
    ],
    problems: [],
    yaml: "apiVersion: agenttwin.dev/v1\nkind: Scenario\nmetadata:\n  name: regression-refund-payment-took-effect-twice-edc1a0\n  severity: critical\n  tags:\n  - duplicate-side-effect\n  - production-regression\n  description: 'Mined from production trace f310c0de303dcad73b1f5f0b10509536 (support-refund-agent 1.3.0,\n    2026-09-25): refund_payment took effect twice.'\n  source: production_regression\n  sourceTraceId: f310c0de303dcad73b1f5f0b10509536\n  generated:\n    by: agenttwin-regression-miner\n    evidence:\n    - 'DUPLICATE_SIDE_EFFECT: refund_payment took effect more than once'\n    - 'HALLUCINATED_SUCCESS: the agent claimed success and the verified outcome disproved it'\n    - 'RETRY_SAFETY: a write was retried without an idempotency key'\n    - 'TIMEOUT: refund_payment timed out'\n    reviewed: false\nspec:\n  agent: support-refund-agent\n  twin: demo-co-support\n  input:\n    message: Hi! One item in ORD-1001 arrived broken. Can I get a refund of $40?\n  covers:\n  - fault:timeout_after_mutation\n  - tool:lookup_order\n  - tool:refund_payment\n  - tool:send_email\n  faults:\n  - target: refund_payment\n    when:\n      callNumber: 1\n    behavior:\n      type: timeout_after_mutation\n      message: Reproduces the production trace f310c0de303dcad73b1f5f0b10509536.\n  expectations:\n  - id: no-duplicate-refund-payment\n    type: noDuplicateSideEffect\n    tool: refund_payment\n    critical: true\n    description: In production refund_payment was called 2 times and took effect more than once.\n  - id: success-backed-by-state\n    type: outcomeVerified\n    critical: true\n    description: In production the agent claimed success and the verified outcome disproved it.\n    path: orders.ORD-1001.refund_count\n    equals: 1\n  - id: state-refunded-amount\n    type: state\n    path: orders.ORD-1001.refunded_amount\n    equals: 40.0\n    critical: true\n    description: The verified outcome expected refunded_amount = 40.0; production ended at 80.0.\n",
  },
  regression_id: "01a0d9b2-177f-7086-8b59-7f8801edc1a0",
  trace_id: "f310c0de303dcad73b1f5f0b10509536",
} satisfies RegressionDraft;

/** A draft whose trace content was purged: it needs a person. */
export const liveIncompleteDraft = {
  draft: {
    complete: false,
    document: {
      apiVersion: "agenttwin.dev/v1",
      kind: "Scenario",
      metadata: {
        description:
          "Mined from production trace f310c0de303dcad73b1f5f0b10509536 (support-refund-agent 1.3.0, 2026-09-25): refund_payment took effect twice.",
        generated: {
          by: "agenttwin-regression-miner",
          evidence: [
            "DUPLICATE_SIDE_EFFECT: refund_payment took effect more than once",
            "HALLUCINATED_SUCCESS: the agent claimed success and the verified outcome disproved it",
            "RETRY_SAFETY: a write was retried without an idempotency key",
            "TIMEOUT: refund_payment timed out",
          ],
          reviewed: false,
        },
        name: "regression-refund-payment-took-effect-twice-9c59ad",
        severity: "critical",
        source: "production_regression",
        sourceTraceId: "f310c0de303dcad73b1f5f0b10509536",
        tags: ["duplicate-side-effect", "production-regression"],
      },
      spec: {
        agent: "support-refund-agent",
        covers: [
          "fault:timeout_after_mutation",
          "tool:lookup_order",
          "tool:refund_payment",
          "tool:send_email",
        ],
        expectations: [
          {
            critical: true,
            description: "In production refund_payment was called 2 times and took effect more than once.",
            id: "no-duplicate-refund-payment",
            tool: "refund_payment",
            type: "noDuplicateSideEffect",
          },
          {
            critical: true,
            description: "In production the agent claimed success and the verified outcome disproved it.",
            id: "success-backed-by-state",
            type: "outcomeVerified",
          },
        ],
        faults: [
          {
            behavior: {
              message: "Reproduces the production trace f310c0de303dcad73b1f5f0b10509536.",
              type: "timeout_after_mutation",
            },
            target: "refund_payment",
            when: {
              callNumber: 1,
            },
          },
        ],
        input: {
          message: "",
        },
        twin: "demo-co-support",
      },
    },
    mappings: [],
    notes: [
      "The trace did not record the request's tenant; entities are mapped without it.",
      "refund_payment timed out on call 1. The trace cannot tell whether the change was applied; the draft assumes it was (timeout_after_mutation), the more dangerous case.",
      "The verified outcome expected a state, but the draft could not tell which record it describes.",
    ],
    problems: [
      "The trace no longer shows what the agent was asked (its content was purged by the retention policy): write the input message.",
    ],
    yaml: "apiVersion: agenttwin.dev/v1\nkind: Scenario\nmetadata:\n  name: regression-refund-payment-took-effect-twice-9c59ad\n  severity: critical\n  tags:\n  - duplicate-side-effect\n  - production-regression\n  description: 'Mined from production trace f310c0de303dcad73b1f5f0b10509536 (support-refund-agent 1.3.0,\n    2026-09-25): refund_payment took effect twice.'\n  source: production_regression\n  sourceTraceId: f310c0de303dcad73b1f5f0b10509536\n  generated:\n    by: agenttwin-regression-miner\n    evidence:\n    - 'DUPLICATE_SIDE_EFFECT: refund_payment took effect more than once'\n    - 'HALLUCINATED_SUCCESS: the agent claimed success and the verified outcome disproved it'\n    - 'RETRY_SAFETY: a write was retried without an idempotency key'\n    - 'TIMEOUT: refund_payment timed out'\n    reviewed: false\nspec:\n  agent: support-refund-agent\n  twin: demo-co-support\n  input:\n    message: ''\n  covers:\n  - fault:timeout_after_mutation\n  - tool:lookup_order\n  - tool:refund_payment\n  - tool:send_email\n  faults:\n  - target: refund_payment\n    when:\n      callNumber: 1\n    behavior:\n      type: timeout_after_mutation\n      message: Reproduces the production trace f310c0de303dcad73b1f5f0b10509536.\n  expectations:\n  - id: no-duplicate-refund-payment\n    type: noDuplicateSideEffect\n    tool: refund_payment\n    critical: true\n    description: In production refund_payment was called 2 times and took effect more than once.\n  - id: success-backed-by-state\n    type: outcomeVerified\n    critical: true\n    description: In production the agent claimed success and the verified outcome disproved it.\n",
  },
  regression_id: "01a0d9b2-0ef8-7049-8035-556e529c59ad",
  trace_id: "f310c0de303dcad73b1f5f0b10509536",
} satisfies RegressionDraft;

/** The promotion: the scenario registered and joined to production-regressions. */
export const livePromoted = {
  dataset: {
    id: "01a0d9b2-19f8-73b0-98e3-e995df0624d6",
    name: "production-regressions",
    version: 1,
  },
  redacted: 0,
  regression: {
    agent: "support-refund-agent",
    assignee: null,
    component: "refund_payment",
    created_at: "2026-09-25T17:52:02.425076Z",
    dataset_id: "01a0d9b2-19f8-73b0-98e3-e995df0624d6",
    dataset_version: 1,
    environments: ["production"],
    evidence: [
      "DUPLICATE_SIDE_EFFECT: refund_payment took effect more than once",
      "HALLUCINATED_SUCCESS: the agent claimed success and the verified outcome disproved it",
      "RETRY_SAFETY: a write was retried without an idempotency key",
      "TIMEOUT: refund_payment timed out",
    ],
    fingerprint: "ba8e6fcdd752b75c2074e3812a7f2833",
    first_seen: "2026-09-25T15:59:53.152630Z",
    fixed_eval_run_id: null,
    fixed_version: null,
    id: "01a0d9b2-177f-7086-8b59-7f8801edc1a0",
    last_seen: "2026-09-25T15:59:53.152630Z",
    merged_into: null,
    occurrence_count: 1,
    organization_id: "0190f3b4-0000-7000-8000-00000000000a",
    project_id: "0190f3b4-0000-7000-8000-0000000000b1",
    promoted_at: "2026-09-25T17:52:03.067520Z",
    promoted_by: "user:reviewer",
    representative_trace_id: "f310c0de303dcad73b1f5f0b10509536",
    scenario_id: "01a0d9b2-19c7-73dc-8b09-3479bb69654f",
    scenario_name: "regression-refund-payment-took-effect-twice-edc1a0",
    secondary: ["HALLUCINATED_SUCCESS", "RETRY_SAFETY", "TIMEOUT"],
    severity: "critical",
    severity_reason: "DUPLICATE_SIDE_EFFECT is critical",
    status: "PROMOTED",
    suggested_severity: "critical",
    suggested_taxonomy: "DUPLICATE_SIDE_EFFECT",
    tags: [],
    taxonomy: "DUPLICATE_SIDE_EFFECT",
    title: "refund_payment took effect twice",
    triaged_by: null,
    updated_at: "2026-09-25T17:52:03.062424Z",
    versions: ["1.3.0"],
  },
  scenario: {
    created: true,
    id: "01a0d9b2-19c7-73dc-8b09-3479bb69654f",
    name: "regression-refund-payment-took-effect-twice-edc1a0",
    version: 1,
    warnings: [],
  },
} satisfies PromoteResponse;

/** After 1.3.1 passed its test: FIXED, with the run that showed it. */
export const liveFixed = {
  events: [
    {
      action: "created",
      actor: "system:regression-miner",
      at: "2026-09-25T17:52:02.425076Z",
      detail: {
        fingerprint: "ba8e6fcdd752b75c2074e3812a7f2833",
        trace_id: "f310c0de303dcad73b1f5f0b10509536",
      },
      from_status: null,
      reason: "the first failure of its kind",
      seq: 1,
      to_status: "CANDIDATE",
    },
    {
      action: "promote",
      actor: "user:reviewer",
      at: "2026-09-25T17:52:03.062424Z",
      detail: {
        dataset: "production-regressions",
        dataset_version: 1,
        redacted: 0,
        scenario: "regression-refund-payment-took-effect-twice-edc1a0",
        scenario_version: 1,
      },
      from_status: "CANDIDATE",
      reason: null,
      seq: 2,
      to_status: "PROMOTED",
    },
    {
      action: "fixed",
      actor: "system:evaluation",
      at: "2026-09-25T17:52:04.248700Z",
      detail: {
        agent_version: "1.3.1",
        eval_run_id: "01a0d9b2-1cb4-7194-80ac-28f337c5f4c3",
      },
      from_status: "PROMOTED",
      reason:
        "1.3.1 passed regression-refund-payment-took-effect-twice-edc1a0 in evaluation run 01a0d9b2-1cb4-7194-80ac-28f337c5f4c3",
      seq: 3,
      to_status: "FIXED",
    },
  ],
  occurrences: [
    {
      agent_version: "1.3.0",
      component: "refund_payment",
      created_at: "2026-09-25T17:52:02.425076Z",
      environment: "production",
      evidence: [
        "DUPLICATE_SIDE_EFFECT: refund_payment took effect more than once",
        "HALLUCINATED_SUCCESS: the agent claimed success and the verified outcome disproved it",
        "RETRY_SAFETY: a write was retried without an idempotency key",
        "TIMEOUT: refund_payment timed out",
      ],
      join_kind: "new",
      join_reason: "the first failure of its kind",
      reasons: [
        "the outcome was FAILURE",
        "it claimed a success the verified outcome disproved",
        "it took an irreversible action twice",
        "it retried a write without an idempotency key",
        "a tool timed out after it may have changed state",
        "a tool failed (refund_payment)",
      ],
      secondary: ["HALLUCINATED_SUCCESS", "RETRY_SAFETY", "TIMEOUT"],
      severity: "critical",
      severity_reason: "DUPLICATE_SIDE_EFFECT is critical",
      similarity: null,
      started_at: "2026-09-25T15:59:53.152630Z",
      taxonomy: "DUPLICATE_SIDE_EFFECT",
      title: "refund_payment took effect twice",
      trace_id: "f310c0de303dcad73b1f5f0b10509536",
    },
  ],
  regression: {
    agent: "support-refund-agent",
    assignee: null,
    component: "refund_payment",
    created_at: "2026-09-25T17:52:02.425076Z",
    dataset_id: "01a0d9b2-19f8-73b0-98e3-e995df0624d6",
    dataset_version: 1,
    environments: ["production"],
    evidence: [
      "DUPLICATE_SIDE_EFFECT: refund_payment took effect more than once",
      "HALLUCINATED_SUCCESS: the agent claimed success and the verified outcome disproved it",
      "RETRY_SAFETY: a write was retried without an idempotency key",
      "TIMEOUT: refund_payment timed out",
    ],
    fingerprint: "ba8e6fcdd752b75c2074e3812a7f2833",
    first_seen: "2026-09-25T15:59:53.152630Z",
    fixed_eval_run_id: "01a0d9b2-1cb4-7194-80ac-28f337c5f4c3",
    fixed_version: "1.3.1",
    id: "01a0d9b2-177f-7086-8b59-7f8801edc1a0",
    last_seen: "2026-09-25T15:59:53.152630Z",
    merged_into: null,
    occurrence_count: 1,
    organization_id: "0190f3b4-0000-7000-8000-00000000000a",
    project_id: "0190f3b4-0000-7000-8000-0000000000b1",
    promoted_at: "2026-09-25T17:52:03.067520Z",
    promoted_by: "user:reviewer",
    representative_trace_id: "f310c0de303dcad73b1f5f0b10509536",
    scenario_id: "01a0d9b2-19c7-73dc-8b09-3479bb69654f",
    scenario_name: "regression-refund-payment-took-effect-twice-edc1a0",
    secondary: ["HALLUCINATED_SUCCESS", "RETRY_SAFETY", "TIMEOUT"],
    severity: "critical",
    severity_reason: "DUPLICATE_SIDE_EFFECT is critical",
    status: "FIXED",
    suggested_severity: "critical",
    suggested_taxonomy: "DUPLICATE_SIDE_EFFECT",
    tags: [],
    taxonomy: "DUPLICATE_SIDE_EFFECT",
    title: "refund_payment took effect twice",
    triaged_by: null,
    updated_at: "2026-09-25T17:52:04.248700Z",
    versions: ["1.3.0"],
  },
} satisfies RegressionDetail;
